### ISSUE TITLE
运行并行例子多处报错

### ISSUE THREAD

**Issue by xiezhipeng-git** [PaddlePaddle/PARL#1023]
参照 Parl\parl\PARL\examples\IMPALA.README.md
在windows powershell中运行
xparl start --port 8010 --cpu_num 32（本地电脑cpu8改不改一样报错）
1.Fail to start the log server.
（这里如果用wsl 的bash里运行上述命令，就可以正常开启log server 其他报错和windows一样）

2.Error: Can not import paddle core while this file exists: C:\Users\hasee\AppData\Local\Programs\Python\python-3.9.13\lib\site-packages\paddle\fluid\libpaddle.pyd

3.OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "C:\Users\hasee\AppData\Local\Programs\Python\python-3.9.13\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
（这里修改了虚拟内存最小10G，最大50G 也报错，自动管理虚拟内存也报错）
Traceback (most recent call last):
  File "C:\Users\hasee\AppData\Local\Programs\Python\python-3.9.13\lib\site-packages\parl\remote\job.py", line 21, in <module>
    import compatible_trick
  File "C:\Users\hasee\AppData\Local\Programs\Python\python-3.9.13\lib\site-packages\parl\remote\compatible_trick.py", line 31, in <module>
    from parl.utils import _IS_MAC
  File "C:\Users\hasee\AppData\Local\Programs\Python\python-3.9.13\lib\site-packages\parl\__init__.py", line 22, in <module>        
    from parl.utils.utils import _HAS_FLUID, _HAS_TORCH, _HAS_PADDLE
  File "C:\Users\hasee\AppData\Local\Programs\Python\python-3.9.13\lib\site-packages\parl\utils\__init__.py", line 16, in <module>  
    from parl.utils.utils import *
  File "C:\Users\hasee\AppData\Local\Programs\Python\python-3.9.13\lib\site-packages\parl\utils\utils.py", line 88, in <module>     
    import torch
  File "C:\Users\hasee\AppData\Local\Programs\Python\python-3.9.13\lib\site-packages\torch\__init__.py", line 129, in <module>      
    raise err

**Comment by TomorrowIsAnOtherDay** [comment]
Windows 环境下，建议使用anaconda安装parl。
你这个报错信息有提及fluid，目前我们不建议使用paddle1.0-fluid版本，建议安装paddle2.0+使用最新的example代码。

**Comment by xiezhipeng-git** [comment]
这个就是2.+的example啊，昨天刚更新的develop分支。是不是运行到了用pip install pal 路径的内容，这些内容有问题。我应该卸载parl。然后修改以后在尝试？

**Comment by xiezhipeng-git** [comment]
是解决了？为什么关闭了？哪里更新了。如果没有更新，问题仍然存在。为什么关闭？而且paddle那边验证的部分和这也没关系

**Comment by TomorrowIsAnOtherDay** [comment]
Windows 环境下，建议使用anaconda安装parl。

**Comment by xiezhipeng-git** [comment]
> Windows 环境下，建议使用anaconda安装parl。

我确实不是使用的anaconda安装的。是直接Python pip 安装的。但是，不管我使用的哪种安装方式。问题就是问题。仍然存在。应该放着。直到解决了才关闭啊。如果这样处理，那问题怎么解决？状态不恢复我重新提交了

**Comment by TomorrowIsAnOtherDay** [comment]
提了建议不参考，那怎么继续呢？
