### ISSUE TITLE
module 'parl' has no attribute 'remote_class'

### ISSUE THREAD

**Issue by Tianyi-Lin** [PaddlePaddle/PARL#1089]
运行example中的PPO train.py时出现上述问题
[04-09 16:11:24 MainThread @utils.py:77] paddlepaddle version: 2.4.2.
Traceback (most recent call last):
  File "C:\Users\123\Desktop\PPO\train.py", line 21, in <module>
    from env_utils import ParallelEnv, LocalEnv
  File "C:\Users\123\Desktop\PPO\env_utils.py", line 164, in <module>
    @parl.remote_class(wait=False)
AttributeError: module 'parl' has no attribute 'remote_class'

版本信息
paddlepaddle = 2.4.2
parl =2.2.1

**Comment by TomorrowIsAnOtherDay** [comment]
hello，windows目前尚不支持remote_class呢。感谢你的反馈，我们短期先增加windows的不支持提示，后续会逐步解决windows的并行兼容性问题。

**Comment by 18699502246** [comment]
Traceback (most recent call last):
  File "F:\CODE\Code\PARL-develop\PARL-develop\examples\QuickStart\train.py", line 21, in <module>
    from cartpole_model import CartpoleModel
  File "F:\CODE\Code\PARL-develop\PARL-develop\examples\QuickStart\cartpole_model.py", line 21, in <module>
    class CartpoleModel(parl.Model):
AttributeError: module 'parl' has no attribute 'Model'
类似报错
parl == 2.2.1
gym == 0.26.2

**Comment by lufengWong** [comment]
win使用paddlepaddle-2.2.1

**Comment by ChangW12138** [comment]
你好，现在win不支持利用@parl.remote_class来进行多线程吗
