### ISSUE TITLE
Facing errors running the liftsim baseline 

### ISSUE THREAD

**Issue by dineshresearch** [PaddlePaddle/PARL#1102]
@TomorrowIsAnOtherDay  I am unable to run the Liftsim baseline PARL/examples/LiftSim_baseline/DQN/ and facing the below error.  Can any one please help me kindly. 

**Environment**
python 3.6.1
gym==0.18
paddlepaddle==1.8.5 cpu (as i could not find the cpu wheel for 1.5.1 and unable to compile it myself i have installed 1.8.5 wheel through pip)
parl= (https://github.com/PaddlePaddle/PARL/tree/r1.3) branch 
rlschool==0.0.1

python demo.py
[05-25 10:28:49 MainThread @logger.py:224] Argv: demo.py
iterations: 100000000
Traceback (most recent call last):
  File "demo.py", line 48, in <module>
    run_main(sys.argv[1:])
  File "demo.py", line 41, in run_main
    dispatcher = RL_dispatcher(mansion_env, args.iterations)
  File "/content/PARL/examples/LiftSim_baseline/DQN/rl_benchmark/dispatcher.py", line 53, in __init__
    self._algorithm = DQN(self._model, hyperparas)
  File "/usr/local/lib/python3.6/dist-packages/parl/algorithms/fluid/dqn.py", line 39, in __init__
    assert isinstance(act_dim, int)
AssertionError

**Comment by dineshresearch** [comment]
I have commented out that assert part but now i am facing the below error
python demo.py
iterations: 100000000
<rl_benchmark.model.RLDispatcherModel object at 0x7f1b5a1a50f0>
{'action_dim': 22, 'lr': 0.0005, 'gamma': 0.998}
[05-25 11:46:24 MainThread @machine_info.py:84] Cannot find available GPU devices, using CPU now.
Traceback (most recent call last):
  File "demo.py", line 48, in <module>
    run_main(sys.argv[1:])
  File "demo.py", line 41, in run_main
    dispatcher = RL_dispatcher(mansion_env, args.iterations)
  File "/content/PARL/examples/LiftSim_baseline/DQN/rl_benchmark/dispatcher.py", line 56, in __init__
    self._act_dim)
  File "/content/PARL/examples/LiftSim_baseline/DQN/rl_benchmark/agent.py", line 34, in __init__
    super(ElevatorAgent, self).__init__(algorithm)
  File "/usr/local/lib/python3.6/dist-packages/parl/core/fluid/agent.py", line 80, in __init__
    self.build_program()
  File "/content/PARL/examples/LiftSim_baseline/DQN/rl_benchmark/agent.py", line 64, in build_program
    self._value = self.alg.define_predict(obs)
AttributeError: 'DQN' object has no attribute 'define_predict'
