### ISSUE TITLE
运行后self.build_program()报错

### ISSUE THREAD

**Issue by lzlbit123** [PaddlePaddle/PARL#1109]
按照课上讲的代码policy gradient 运行后报错raise NotImplementedError

<img width="668" alt="1688715375418" src="https://github.com/PaddlePaddle/PARL/assets/138860074/dfed51d6-26ce-4a61-b8d9-0dc7a83911b9">
Traceback (most recent call last):
  File "C:\Users\lzlbi\PycharmProjects\PPO\train.py", line 86, in <module>
    main()
  File "C:\Users\lzlbi\PycharmProjects\PPO\train.py", line 63, in main
    agent = Agent(alg, obs_dim=obs_dim, act_dim=act_dim)
  File "C:\Users\lzlbi\PycharmProjects\PPO\agent.py", line 11, in __init__
    super(Agent, self).__init__(algorithm)
  File "D:\anaconda\envs\paddle\lib\site-packages\parl\core\fluid\agent.py", line 81, in __init__
    self.build_program()
  File "C:\Users\lzlbi\PycharmProjects\PPO\agent.py", line 20, in build_program
    self.act_prob = self.alg.predict(obs)
  File "D:\anaconda\envs\paddle\lib\site-packages\parl\core\fluid\algorithm.py", line 196, in predict
    raise NotImplementedError
NotImplementedError
版本：parl==1.4
           paddle paddle==1.8.5
           gym==0.18.0
           Python ==3.7.7

**Comment by lzlbit123** [comment]
另外，课程中的代码是否需要定义是否启用GPU运算？

**Comment by P90-RushB** [comment]
课程中代码无需gpu版paddle即可运行。该报错提示是paddle安装又问题。推荐在win中使用wsl或docker，在linux环境中运行，实测没有问题。可以参考该[链接](https://github.com/PaddlePaddle/PARL/tree/88af2676301372f52d02a5df671847a12dcc8a2e/examples/tutorials)安装步骤。
