### ISSUE TITLE
train.py导入parl时报错怎么解决

### ISSUE THREAD

**Issue by Pingpongdragon** [PaddlePaddle/PARL#1120]
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    import parl
  File "/home/ljy/.local/lib/python3.8/site-packages/parl/__init__.py", line 54, in <module>
    from parl.remote import remote_class, connect
  File "/home/ljy/.local/lib/python3.8/site-packages/parl/remote/__init__.py", line 19, in <module>
    from parl.remote.remote_decorator import *
  File "/home/ljy/.local/lib/python3.8/site-packages/parl/remote/remote_decorator.py", line 20, in <module>
    from parl.remote.remote_wrapper import RemoteWrapper
  File "/home/ljy/.local/lib/python3.8/site-packages/parl/remote/remote_wrapper.py", line 22, in <module>
    from parl.remote.communication import loads_argument, loads_return,\
  File "/home/ljy/.local/lib/python3.8/site-packages/parl/remote/communication.py", line 38, in <module>
    context = pyarrow.default_serialization_context()
  File "/home/ljy/.local/lib/python3.8/site-packages/pyarrow/__init__.py", line 316, in __getattr__
    raise AttributeError(
AttributeError: module 'pyarrow' has no attribute 'default_serialization_context'

**Comment by TomorrowIsAnOtherDay** [comment]
hello，请提供你的系统环境信息，python 环境、系统版本、parl版本等

**Comment by Pingpongdragon** [comment]
ubuntu linux系统,版本号20.04 ，python版本3.8.10，parl导入未成功
![图片](https://github.com/PaddlePaddle/PARL/assets/88362726/d22d7ffa-6d95-4f6e-a4f9-335c10c491d8)
![图片](https://github.com/PaddlePaddle/PARL/assets/88362726/c7d34922-91a9-4bd5-8321-d497640a9bc8)
![图片](https://github.com/PaddlePaddle/PARL/assets/88362726/e4c9a7f9-7e55-4e89-b6d2-4622df39e65d)

**Comment by 1zeryu** [comment]
我也是这个问题：
系统环境：HOSTNAME=464884fd017f
NOTVISIBLE=in users profile
NV_LIBNPP_VERSION=11.7.3.21-1
NV_NVPROF_DEV_PACKAGE=cuda-nvprof-11-7=11.7.50-1
NVIDIA_VISIBLE_DEVICES=all
NV_NVPROF_VERSION=11.7.50-1
NV_LIBCUSPARSE_VERSION=11.7.3.50-1
NVIDIA_PRODUCT_NAME=CUDA
NV_LIBCUBLAS_DEV_PACKAGE=libcublas-dev-11-7=11.10.1.25-1
NCCL_VERSION=2.13.4-1
PWD=/home/ysocr
NVARCH=x86_64
HOME=/root
NV_LIBCUSPARSE_DEV_VERSION=11.7.3.50-1
NVIDIA_CUDA_END_OF_LIFE=1
NV_LIBNCCL_PACKAGE_VERSION=2.13.4-1
NV_LIBNCCL_PACKAGE=libnccl2=2.13.4-1+cuda11.7
NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
NV_CUDA_LIB_VERSION=11.7.0-1
NV_LIBNPP_PACKAGE=libnpp-11-7=11.7.3.21-1
NV_LIBNCCL_PACKAGE_NAME=libnccl2
LIBRARY_PATH=/usr/local/cuda/lib64/stubs
NV_NVTX_VERSION=11.7.50-1
NV_LIBCUBLAS_VERSION=11.10.1.25-1
NV_LIBCUBLAS_PACKAGE=libcublas-11-7=11.10.1.25-1
NV_CUDNN_VERSION=8.5.0.96
NV_CUDA_CUDART_DEV_VERSION=11.7.60-1
TERM=xterm
NV_NVML_DEV_VERSION=11.7.50-1
CUDA_VERSION=11.7.0
NV_LIBCUBLAS_PACKAGE_NAME=libcublas-11-7
NVIDIA_DRIVER_CAPABILITIES=compute,utility
SHLVL=1
NV_LIBCUBLAS_DEV_PACKAGE_NAME=libcublas-dev-11-7
NVIDIA_REQUIRE_CUDA=cuda>=11.7 brand=tesla,driver>=450,driver<451 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=510,driver<511 brand=unknown,driver>=510,driver<511 brand=nvidia,driver>=510,driver<511 brand=nvidiartx,driver>=510,driver<511 brand=quadro,driver>=510,driver<511 brand=quadrortx,driver>=510,driver<511 brand=titan,driver>=510,driver<511 brand=titanrtx,driver>=510,driver<511 brand=geforce,driver>=510,driver<511 brand=geforcertx,driver>=510,driver<511
NV_LIBNPP_DEV_VERSION=11.7.3.21-1
NV_CUDA_CUDART_VERSION=11.7.60-1
NV_CUDNN_PACKAGE_NAME=libcudnn8
PATH=/home/venv/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NV_LIBNCCL_DEV_PACKAGE_VERSION=2.13.4-1
NV_CUDNN_PACKAGE=libcudnn8=8.5.0.96-1+cuda11.7
Python: 3.8.0
parl版本：2.2.1

**Comment by natureLanguageQing** [comment]
我也遇到了这个问题 default_serialization_context

**Comment by natureLanguageQing** [comment]
pip install -U pyarrow==8.0.0

**Comment by natureLanguageQing** [comment]
建议官方修改为
```FutureWarning: 'pyarrow.default_serialization_context' is deprecated as of 2.0.0 and will be removed in a future version. Use pickle or the pyarrow IPC functionality instead.
  context = pyarrow.default_serialization_context()
```
