### ISSUE TITLE
渲染图像render=True时，代码报错，图像框一下子闪退 Windows10

### ISSUE THREAD

**Issue by SusanJJJ** [PaddlePaddle/PARL#1131]
报错内容    
Traceback (most recent call last):
  File "D:\code\homework\ddpg_quadrotor\train.py", line 184, in <module>
    main()
  File "D:\code\homework\ddpg_quadrotor\train.py", line 162, in main
    avg_reward = run_evaluate_episodes(
  File "D:\code\homework\ddpg_quadrotor\train.py", line 123, in run_evaluate_episodes
    env.render()
  File "D:\code\homework\ddpg_quadrotor\train.py", line 60, in render
    self.env.render()
  File "D:\anacondainstall\envs\rlnew\lib\site-packages\rlschool\quadrotor\env.py", line 166, in render
    self.viewer = RenderWindow(task=self.task,
  File "D:\anacondainstall\envs\rlnew\lib\site-packages\rlschool\quadrotor\render.py", line 489, in __init__
    self.internal_map = Map(
  File "D:\anacondainstall\envs\rlnew\lib\site-packages\rlschool\quadrotor\render.py", line 117, in __init__
    self._initialize(init_drone_z)
  File "D:\anacondainstall\envs\rlnew\lib\site-packages\rlschool\quadrotor\render.py", line 130, in _initialize
    self._add_drone()
  File "D:\anacondainstall\envs\rlnew\lib\site-packages\rlschool\quadrotor\render.py", line 152, in _add_drone
    if geometry_hash(geom) == self.drone_vertex_list_hash:
  File "D:\anacondainstall\envs\rlnew\lib\site-packages\rlschool\quadrotor\utils.py", line 113, in geometry_hash
    md5 += str(geometry.visual.crc())
UnboundLocalError: local variable 'md5' referenced before assignment

**Comment by FNeng** [comment]
提前定义发现还是报错crc()缺失，搜了下发现解决办法是把trimesh包降低到trimesh<=3.15.1就行，我降到3.15.1就解决了
