### ISSUE TITLE
Attributerror

### ISSUE THREAD

**Issue by spiderZhengLi** [PaddlePaddle/PARL#1135]
(paddle) F:\Desktop\PARL-develop\examples\QuickStart>python train.py
[32m[03-23 22:43:02 MainThread @logger.py:242][0m Argv: train.py
[33m[03-23 22:43:04 MainThread @__init__.py:37][0m [5m[33mWRN[0m No deep learning framework was found, but it's ok for parallel computation.
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from cartpole_model import CartpoleModel
  File "F:\Desktop\PARL-develop\examples\QuickStart\cartpole_model.py", line 21, in <module>
    class CartpoleModel(parl.Model):
AttributeError: module 'parl' has no attribute 'Model'

**Comment by FANTASY-Xxx** [comment]
me too

**Comment by TomorrowIsAnOtherDay** [comment]
The error message shows that you have not yet installed any deep learning framework. Please install PaddlePaddle before running the training script.

**Comment by spiderZhengLi** [comment]
I'sure that I have installed the paddlepaddle and parl.After that,I still have the error.

**Comment by TomorrowIsAnOtherDay** [comment]
Hey, guys, could you give me the system info and tell me which Paddle version you're using? That way, I can try to replicate the error on my end.

**Comment by spiderZhengLi** [comment]
I am using a Windows 11 system, and the graphics card is an NVIDIA GeForce RTX 3060 Laptop GPU. The paddlepaddle version I use is 2.6.1, the parl version is 2.2.1, and the python version is 3.8.

**Comment by 1Northward1** [comment]
me too
![image](https://github.com/PaddlePaddle/PARL/assets/46013929/f0d6535b-5bb6-420e-be2d-d3a2875a2b7e)

**Comment by lufengWong** [comment]
win使用paddlepaddle-2.2.1
