### ISSUE TITLE
WRN No deep learning framework was found, but it's ok for parallel computation.

### ISSUE THREAD

**Issue by lmy235638** [PaddlePaddle/PARL#1149]
**python环境**:3.8
**paddle-gpu版本**:2.6.1,安装方式为:`conda install paddlepaddle-gpu==2.6.1 cudatoolkit=11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge`
**parl版本:2.2.1**,安装方式为`pip install parl`

**出现问题**:paddle使用正常,但在`import parl`时会出现`WRN No deep learning framework was found, but it's ok for parallel computation.`警告.运行[快速入门：解决CartPole问题](https://parl.readthedocs.io/zh-cn/latest/tutorial/getting_started.html)时会出现`parl没有model的报错`

**尝试解决方法**:降级paddle为2.5版本正常使用

请问parl现在不支持paddle最新版本2.6吗

**Comment by TomorrowIsAnOtherDay** [comment]
赞解决方案的同步，应该是支持的。
你可以试试安装parl + paddle2.6，然后执行
```shell
python -c "import paddle"
```
看看有没有报错信息。

**Comment by 18684031838** [comment]
我用paddle2.5.0和python3.8运行示例，仍然报错，请问能否提供一个运行所有示例的版本的依赖文件requirements.txt呢？谢谢！
这个是我的报错：
[12-16 06:37:07 MainThread @utils.py:79] paddlepaddle version: 2.5.0.
Traceback (most recent call last):
  File "D:\Source\study\python\paddle\examples\tutorials\lesson3\dqn\train.py", line 30, in <module>
    from model import Model
  File "D:\Source\study\python\paddle\examples\tutorials\lesson3\dqn\model.py", line 18, in <module>
    from parl import layers  # 封装了 paddle.fluid.layers 的API
ImportError: cannot import name 'layers' from 'parl' (D:\Source\study\python\paddle\parl\__init__.py)

**Comment by P90-RushB** [comment]
readme新增了经过测试的最新的安装步骤，可以参考。win版本最高支持到2.2.1

**Comment by P90-RushB** [comment]
Since there has been no further feedback for a long time, I will close this issue for now. If the problem persists, feel free to reopen it or create a new issue.
