### ISSUE TITLE
AttributeError: module 'parl' has no attribute 'Model'

### ISSUE THREAD

**Issue by kaoe3** [PaddlePaddle/PARL#1154]
Traceback (most recent call last):
  File "C:\Users\TJUAE\Downloads\PARL-develop\PARL-develop\examples\QuickStart\train.py", line 21, in <module>
    from cartpole_model import CartpoleModel
  File "C:\Users\TJUAE\Downloads\PARL-develop\PARL-develop\examples\QuickStart\cartpole_model.py", line 21, in <module>
    class CartpoleModel(parl.Model):
AttributeError: module 'parl' has no attribute 'Model'

**Comment by amocken** [comment]
You can solve this by degrading the paddlepaddle from version 2.6 to 2.5.
