### ISSUE TITLE
why is the dqn example not running?

### ISSUE THREAD

**Issue by 18684031838** [PaddlePaddle/PARL#1160]
The python version I'm using is 3.8,and the paddle version is 2.5.0,The error message is as follows:

[12-16 07:04:52 MainThread @logger.py:242] Argv: D:\Source\study\python\paddle\examples\tutorials\lesson3\dqn\train.py
[12-16 07:04:53 MainThread @utils.py:79] paddlepaddle version: 2.5.0.
Traceback (most recent call last):
  File "D:\Source\study\python\paddle\examples\tutorials\lesson3\dqn\train.py", line 30, in <module>
    from model import Model
  File "D:\Source\study\python\paddle\examples\tutorials\lesson3\dqn\model.py", line 18, in <module>
    from parl import layers  # Encapsulates the API of paddle.fluid.layers
ImportError: cannot import name 'layers' from 'parl' (D:\Source\study\python\paddle\parl\__init__.py)

Process finished with exit code 1

Could you provide a requirements.txt file with the latest parl framework and dependencies that will work with the example? Thank you!

**Comment by P90-RushB** [comment]
Under Windows, the currently highest supported paddle version is 2.2.1. You can try installing: pip install paddlepaddle-gpu==2.2.1

**Comment by P90-RushB** [comment]
Since there has been no further feedback for a long time, I will close this issue for now. If the problem persists, feel free to reopen it or create a new issue.
