### ISSUE TITLE
locale.Error: unsupported locale setting in Windows

### ISSUE THREAD

**Issue by mxfengustc** [PaddlePaddle/PARL#157]
Locale setting's error occurred when i run parl in Windows OS
```
C:\Users\mxfeng>xparl start --cpu_num 64 --port 8010 --monitor_port 7777
[32m[09-26 15:08:16 MainThread @logger.py:217] [0m Argv: C:\Users\mxfeng\Anaconda3\envs\dist_deep_rl\Scripts\xparl.exe start --cpu_num 64 --port 8010 --monitor_port 7777
Traceback (most recent call last):
  File "c:\users\mxfeng\anaconda3\envs\dist_deep_rl\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mxfeng\anaconda3\envs\dist_deep_rl\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mxfeng\Anaconda3\envs\dist_deep_rl\Scripts\xparl.exe\__main__.py", line 5, in <module>
  File "c:\users\mxfeng\anaconda3\envs\dist_deep_rl\lib\site-packages\parl\remote\scripts.py", line 36, in <module>
    locale.setlocale(locale.LC_ALL, "en_US.UTF-8")
  File "c:\users\mxfeng\anaconda3\envs\dist_deep_rl\lib\locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
I know how to fix the bug in Ubuntu, but i have no idea in Windows OS

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for your feedback. We had known the issue about using parl in `Windows` platform, and were trying to solve the problem(See #154).
Unfortunately, we found it difficult to manage the processes in `Windows` as the kernel of `windows` is different from that in `Ubuntu`. 
We are now investigating the solution to this issue, and currently, we suggest that you run PARL in linux-based system.

**Comment by mxfengustc** [comment]
ok, thanks a lot~
