### ISSUE TITLE
ValueError: share_vars_from is not compiled and run, so there is no var to share.

### ISSUE THREAD

**Issue by becknian** [PaddlePaddle/PARL#160]
When running `python3 simulator_server.py --port 8030 --ensemble_num 1` within `NeurIPS2018-AI-for-Prosthetics-Challenge`, I got the following error:
```
share_vars_from is set, scope is ignored.
Traceback (most recent call last):
  File "simulator_server.py", line 331, in <module>
    simulator_server = SimulatorServer()
  File "simulator_server.py", line 84, in __init__
    self.agent = OpenSimAgent(alg, OBS_DIM, ACT_DIM, args.ensemble_num)
  File "/home/rsa-key-20191010/test/PARL/examples/NeurIPS2018-AI-for-Prosthetics-Challenge/opensim
_agent.py", line 64, in __init__
    share_vars_parallel_executor=self.learn_pe[i])
  File "/home/rsa-key-20191010/test/PARL/examples/NeurIPS2018-AI-for-Prosthetics-Challenge/multi_h
ead_ddpg.py", line 121, in sync_target
    share_vars_parallel_executor=share_vars_parallel_executor)
  File "/home/davidzhenggd/.local/lib/python3.5/site-packages/parl/core/fluid/model.py", line 182,
 in sync_weights_to
    self._cached_fluid_executor.run(fetch_list=[])
  File "/home/davidzhenggd/.local/lib/python3.5/site-packages/paddle/fluid/parallel_executor.py", 
line 280, in run
    return_numpy=return_numpy)
  File "/home/davidzhenggd/.local/lib/python3.5/site-packages/paddle/fluid/executor.py", line 664,
 in run
    program._compile(scope, self.place)
  File "/home/davidzhenggd/.local/lib/python3.5/site-packages/paddle/fluid/compiler.py", line 376,
 in _compile
    scope=self._scope)
  File "/home/davidzhenggd/.local/lib/python3.5/site-packages/paddle/fluid/compiler.py", line 284,
 in _compile_data_parallel
    "share_vars_from is not compiled and run, so there is no "
ValueError: share_vars_from is not compiled and run, so there is no var to share.
```
Do you know how to resolve this issue? Thanks in advance!

**Comment by TomorrowIsAnOtherDay** [comment]
Please provide the information of your environment such as the version of paddle and parl.

**Comment by becknian** [comment]
cuda 10.0, paddlepaddle-gpu=1.5.2.post107, parl=1.1.3

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks.  We have not tested the compatibility of this folder in Paddle1.5.2. 
To run the code, I suggest you try again after installing Paddle 1.5.1. 
We would not like to update the code to make it compatible with the newest Paddle, as it's hard the  to guarantee its reproducity, especially for a sophisticated RL task like this challenge.

**Comment by becknian** [comment]
Thanks. I tried 1.5.1.post107 and it works!

**Comment by TomorrowIsAnOtherDay** [comment]
Sorry for not giving any hints on the version here. We will be updating the readme in that folder. 

Again, thanks for raising the issue.

**Comment by becknian** [comment]
In my another environment I got this error. Do you know about this?
```
I1011 02:40:49.894224  5714 parallel_executor.cc:329] The number of CUDAPlace, which is used in ParallelExecutor, is 2. And the Program will be copied 2 copies
Traceback (most recent call last):
  File "simulator_server.py", line 327, in <module>
    simulator_server = SimulatorServer()
  File "simulator_server.py", line 84, in __init__
    self.agent = OpenSimAgent(alg, OBS_DIM, ACT_DIM, args.ensemble_num)
  File "/Data/jianian/latest/PARL/examples/NeurIPS2018-AI-for-Prosthetics-Challenge/opensim_agent.py", line 63, in __init__
    share_vars_parallel_executor=self.learn_pe[i])
  File "/Data/jianian/latest/PARL/examples/NeurIPS2018-AI-for-Prosthetics-Challenge/multi_head_ddpg.py", line 121, in sync_target
    share_vars_parallel_executor=share_vars_parallel_executor)
  File "/usr/local/lib/python3.5/dist-packages/parl/core/fluid/model.py", line 177, in sync_weights_to
    build_strategy=build_strategy,
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/parallel_executor.py", line 175, in __init__
    self._compiled_program._compile(place=self._place, scope=self._scope)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/compiler.py", line 368, in _compile
    scope=self._scope)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/compiler.py", line 339, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core_avx.EnforceNotMet: Enforce failed. Expected member_->places_.size() == local_scopes.size(), but received member_->places_.size():2 != local_scopes.size():1.
 at [/paddle/paddle/fluid/framework/parallel_executor.cc:344]
PaddlePaddle Call Stacks:
0       0x7f71826f6d98p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f71826f70e7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f71828d17d4p paddle::framework::ParallelExecutor::ParallelExecutor(std::vector<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::allocator<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > const&, std::vector<std::string, std::allocator<std::string> > const&, std::string const&, paddle::framework::Scope*, std::vector<paddle::framework::Scope*, std::allocator<paddle::framework::Scope*> > const&, paddle::framework::details::ExecutionStrategy const&, paddle::framework::details::BuildStrategy const&, paddle::framework::ir::Graph*) + 8852
3       0x7f7182789e78p
4       0x7f7182729186p
5             0x4ea117p PyCFunction_Call + 119
6             0x5bc037p PyObject_Call + 71
7             0x4f489ep
8             0x5bc037p PyObject_Call + 71
9             0x54e9b9p
10            0x55851cp
11            0x5bc037p PyObject_Call + 71
12            0x528cefp PyEval_EvalFrameEx + 20239
13            0x52d2b9p
14            0x528ee2p PyEval_EvalFrameEx + 20738
15            0x52d2b9p
16            0x529333p PyEval_EvalFrameEx + 21843
17            0x52e10bp PyEval_EvalCodeEx + 315
18            0x4ec487p
19            0x5bc037p PyObject_Call + 71
20            0x4f489ep
21            0x5bc037p PyObject_Call + 71
22            0x54e9b9p
23            0x55851cp
24            0x5bc037p PyObject_Call + 71
25            0x528cefp PyEval_EvalFrameEx + 20239
26            0x52d2b9p
27            0x528ee2p PyEval_EvalFrameEx + 20738
28            0x52d2b9p
29            0x528ee2p PyEval_EvalFrameEx + 20738
30            0x52e84ap PyEval_EvalCodeEx + 2170
31            0x4ec373p
32            0x5bc037p PyObject_Call + 71
33            0x4f489ep
34            0x5bc037p PyObject_Call + 71
35            0x54e9b9p
36            0x55851cp
37            0x5bc037p PyObject_Call + 71
38            0x528cefp PyEval_EvalFrameEx + 20239
39            0x52e10bp PyEval_EvalCodeEx + 315
40            0x4ec373p
41            0x5bc037p PyObject_Call + 71
42            0x4f489ep
43            0x5bc037p PyObject_Call + 71
44            0x54e9b9p
45            0x55851cp
46            0x5bc037p PyObject_Call + 71
47            0x528cefp PyEval_EvalFrameEx + 20239
48            0x52d2b9p
49            0x52dfbfp PyEval_EvalCode + 31
50            0x5fc652p
51            0x5feafap PyRun_FileExFlags + 154
52            0x5fececp PyRun_SimpleFileExFlags + 444
53            0x63ec96p Py_Main + 1110
54            0x4d02e1p main + 225
55      0x7f71fb4ba830p __libc_start_main + 240
56            0x5d4b99p _start + 41
```

**Comment by TomorrowIsAnOtherDay** [comment]
Could you try using only a GPU by running the following command:
`export CUDA_VISIBLE_DEVICES="0"`

**Comment by becknian** [comment]
Sweet! This also works. Thanks a lot.

**Comment by TomorrowIsAnOtherDay** [comment]
Great!
Paddle tries to use multiple GPU at the same time, but in fact, we only need a GPU for this task.
