### ISSUE TITLE
AssertionError: The loss_name should be set here.

### ISSUE THREAD

**Issue by luoruiming** [PaddlePaddle/PARL#185]
When running `sh scripts/train_difficulty1.sh ./low_speed_model`  in /PARL/examples/NeurIPS2019-Learn-to-Move-Challenge, an AssertionError occurred.

`(opensim-rl) luo@idserver:~/PARL/examples/NeurIPS2019-Learn-to-Move-Challenge$ sh scripts/train_difficulty1.sh ./low_speed_model

/home/luo/anaconda3/envs/opensim-rl/bin/python
[12-15 11:41:49 MainThread @logger.py:224] Argv: train.py --actor_num 300 --difficulty 1 --penalty_coeff 3.0 --logdir ./output/difficulty1 --restore_model_path ./low_speed_model
/home/luo/anaconda3/envs/opensim-rl/lib/python3.6/site-packages/opensim/simbody.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[12-15 11:41:49 MainThread @machine_info.py:86] nvidia-smi -L found gpu count: 4
[12-15 11:41:49 MainThread @machine_info.py:86] nvidia-smi -L found gpu count: 4
W1215 11:41:50.501416 31581 device_context.cc:235] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.0, Runtime API Version: 10.0
W1215 11:41:50.504907 31581 device_context.cc:243] device: 0, cuDNN Version: 7.5.
[12-15 11:41:51 MainThread @machine_info.py:86] nvidia-smi -L found gpu count: 4
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    learner = Learner(args)
  File "train.py", line 78, in __init__
    self.agent = OpenSimAgent(algorithm, OBS_DIM, ACT_DIM)
  File "/home/luo/PARL/examples/NeurIPS2019-Learn-to-Move-Challenge/opensim_agent.py", line 40, in __init__
    build_strategy=build_strategy)
  File "/home/luo/anaconda3/envs/opensim-rl/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 201, in __init__
    if share_vars_from else None)
  File "/home/luo/anaconda3/envs/opensim-rl/lib/python3.6/site-packages/paddle/fluid/compiler.py", line 244, in with_data_parallel
    assert self._loss_name is not None, "The loss_name should be set here."
AssertionError: The loss_name should be set here.
`

Does anybody know how to solve that? Thanks in advance.

**Comment by zenghsh3** [comment]
Hi, it may be raised by the wrong paddlepaddle version.
Can you try `paddlepaddle-gpu==1.5.1` and `parl==1.2.1`, and run `export CUDA_VISIBLE_DEVICES=0` in terminal to use one GPU device.
We also refine the scripts in this [PR](https://github.com/PaddlePaddle/PARL/pull/186) .

**Comment by luoruiming** [comment]
Nailed it! Thanks!
