### ISSUE TITLE
Error: Paddle internal Check failed.

### ISSUE THREAD

**Issue by zienn** [PaddlePaddle/PARL#233]
在impala基础上的改动，运行出现如下错误。运行其他算法没有问题。
```
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::ReadOp::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
3   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
4   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
5   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/xtq/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/xtq/anaconda3/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/xtq/anaconda3/lib/python3.6/site-packages/paddle/fluid/layers/io.py", line 872, in read_file
    type='read', inputs={'Reader': [reader]}, outputs={'Out': out})
  File "/home/xtq/DVTrace v2.3.1/atari_agent.py", line 74, in build_program
    self.learn_reader)
  File "/home/xtq/anaconda3/lib/python3.6/site-packages/parl/core/fluid/agent.py", line 87, in __init__
    self.build_program()
  File "/home/xtq/DVTrace v2.3.1/atari_agent.py", line 29, in __init__
    super(AtariAgent, self).__init__(algorithm)
  File "train.py", line 65, in __init__
    self.learn_data_provider)
  File "train.py", line 276, in <module>
    learner = Learner(config)

----------------------
Error Message Summary:
----------------------
Error: Paddle internal Check failed. (Please help us create a new issue, here we need to find the developer to add a user friendly error message)
  [Hint: Expected ins.size() == out_arg_names.size(), but received ins.size():9 != out_arg_names.size():8.] at (/paddle/paddle/fluid/operators/reader/read_op.cc:92)
  [operator < read > error]
```

**Comment by zienn** [comment]
大概是learn_program地方出问题
```
/home/xtq/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/xtq/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/xtq/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 153, in run_learn
    total_loss, pi_loss, vf_loss, entropy, kl = self.agent.learn()
  File "/home/xtq/DVTrace v2.3.1/atari_agent.py", line 122, in learn
    self.learn_program, fetch_list=self.learn_outputs)
  File "/home/xtq/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/home/xtq/anaconda3/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/xtq/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/home/xtq/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 822, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/xtq/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 899, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:
```

**Comment by zenghsh3** [comment]
看下面错误提示应该是输入数据size和定义的输入tensor size不一致？
Hint: Expected ins.size() == out_arg_names.size(), but received ins.size():9 != out_arg_names.size():8.

**Comment by zienn** [comment]
谢谢，解决了

**Comment by TomorrowIsAnOtherDay** [comment]
请问你有在做什么酷炫的事情吗？：）
可以的话请同步下给我们，作为开发者我们也很想知道用户用它干了什么，哈哈

**Comment by zienn** [comment]
> 请问你有在做什么酷炫的事情吗？：）
> 可以的话请同步下给我们，作为开发者我们也很想知道用户用它干了什么，哈哈

可是我觉得我没什么贡献【捂脸】，只是把IMPALA用在连续动作控制环境。

**Comment by TomorrowIsAnOtherDay** [comment]
> > 请问你有在做什么酷炫的事情吗？：）
> > 可以的话请同步下给我们，作为开发者我们也很想知道用户用它干了什么，哈哈
> 
> 可是我觉得我没什么贡献【捂脸】，只是把IMPALA用在连续动作控制环境。

哈哈，还是感谢你对于PARL的支持！
