### ISSUE TITLE
请问ppo如何能平行计算

### ISSUE THREAD

**Issue by wujiren** [PaddlePaddle/PARL#279]
ppo是on-policy的model，我应该如何设置才能在一台电脑或者多台电脑上进行并行计算？

**Comment by TomorrowIsAnOtherDay** [comment]
你好，目前我们还没有并行版本的PPO。
如果自行开发的话，可以使用我们的并行接口`parl.remote_class` 开发，具体可以参考我们的文档以及A2C这个算法示例。

----------
抱歉，刚手误点了close

**Comment by wujiren** [comment]
> 你好，目前我们还没有并行版本的PPO。
> 如果自行开发的话，可以使用我们的并行接口`parl.remote_class` 开发，具体可以参考我们的文档以及A2C这个算法示例。
> 
> 抱歉，刚手误点了close

感谢您这么快速的答复。
我还想请教一个问题，我自行开发的话，哪个来例子更适合参考？平行版的ppo和其他off-policy的主要区别在哪里？
我自己的想法是把agent发给在多个进程或者多台电脑的节点，作为多个actor平行采样，采样结束后中央节点利用这些返回的数据训练，更新网络的参数。然后再把更新好参数agent发给其他节点，做新一轮的采样。不知道这样的逻辑合不合理，望指点。如果有其他开发上的建议，也希望能得到您的帮助。

**Comment by TomorrowIsAnOtherDay** [comment]
整体思路是没问题的。之前我做调研的时候也开发过（大约两年前）并行版本的PPO，需要注意的一个点是中央节点训练的时候，子节点（actor）上不再收集数据。这个类似A2C一样，收集数据，然后开始训练。建议读懂[A2C example](https://github.com/PaddlePaddle/PARL/tree/develop/examples/A2C) 之后，自行开发，开发过程中有任何问题欢迎提issue。
祝好：）

**Comment by wujiren** [comment]
感谢您的指点，我先看一下这个例子，然后再去尝试开发一下。

**Comment by wujiren** [comment]
您好，我根据A2C的例子，写了PPO平行的框架。目前还只是一个框架，里面有一些具体的方法并没有实现。如果您方便的话可以给我一些指导，看看是否能够更加合理。代码如下，不知道能不能看的清楚。
在调试的过程中，我发现如果@parl.remote_class封装的不是一个基类的话，父类的初始化似乎会出现问题，因此我看到例子里actor都是基类，内部实例化一个agent来作为自己的属性，不知道是不是这样的？

import parl
import gym
import threading
import queue


class MyEnv(gym.Env):
    def __init__(self):
        """
        定义我的环境
        """
        super(MyEnv, self).__init__()


class MyModel(parl.Model):
    def __init__(self, **params):
        """
        定义我的model
        :param params:
        """
        super(MyModel, self).__init__(**params)


class LocalAgent(parl.Agent):
    def __init__(self):
        """
        创建一个中央的PPO agent，用于学习或者在环境中采集的数据
        """
        model = MyModel()
        algorithm = parl.algorithms.PPO(model=model)
        super(LocalAgent, self).__init__(algorithm=algorithm)

    def collect_trajectories(self, env):
        """
        agent和环境交互，收集数据
        :param env:
        :return:
        """
        trajectories = []
        # todo:实现采样的过程
        return trajectories


@parl.remote_class
class RemoteAgent:
    def __init__(self):
        """
        创建一个远程的agent，用于平行计算中采集数据
        """
        self.env = MyEnv()
        # 把本地的agent实例作为自己的属性，用来收集数据
        self.agent = LocalAgent()

    def collect_trajectories(self):
        """
        用agent来采样
        :return:
        """
        return self.agent.collect_trajectories()

    def set_weights(self, weights):
        """
        装载中央的agent的参数
        :param weights:
        :return:
        """
        self.agent.set_weights(weights=weights)


class Learner(object):
    def __init__(self):
        """
        实现平行计算
        """
        self.local_agent = LocalAgent()

    def run_remote_samples(self, weights, trajectories_queue):
        # 创建一个平行计算的agent
        remote_agent = RemoteAgent()
        # load 最新的参数
        remote_agent.set_weights(weights)
        # 收集数据，放到队列中
        trajectories_queue.put(remote_agent.collect_trajectories())

    def step(self):
        cpu_number = 2

        # 用于收集平行actor采样的trajectories
        trajectories_queue = queue.Queue()

        # 发送最新的参数给actor
        local_weights = self.local_agent.get_weights()

        # 开启平行计算的actor
        remote_thread_list = []
        for _ in range(cpu_number):
            remote_thread = threading.Thread(
                target=self.run_remote_samples, args=(local_weights, trajectories_queue))
            remote_thread.setDaemon(True)
            remote_thread.start()

        # 等待数据收集结束
        for t in remote_thread_list:
            t.join()

        # 用收集的数据训练本地的agent
        for _ in range(cpu_number):
            trajectories = trajectories_queue.get()
            self.local_agent.learn(trajectories)


if __name__ == '__main__':
    learner = Learner()
    while True:
        # 不间断的训练
        learner.step()

**Comment by wujiren** [comment]
您好，我根据A2C的例子，写了PPO平行的框架。目前还只是一个框架，里面有一些具体的方法并没有实现。如果您方便的话可以给我一些指导，看看是否能够更加合理。代码如下，不知道能不能看的清楚。
在调试的过程中，我发现如果@parl.remote_class封装的不是一个基类的话，父类的初始化似乎会出现问题，因此我看到例子里actor都是基类，内部实例化一个agent来作为自己的属性，不知道是不是这样的？
```python
import parl
import gym
import threading
import queue


class MyEnv(gym.Env):
    def __init__(self):
        """
        定义我的环境
        """
        super(MyEnv, self).__init__()


class MyModel(parl.Model):
    def __init__(self, **params):
        """
        定义我的model
        :param params:
        """
        super(MyModel, self).__init__(**params)


class LocalAgent(parl.Agent):
    def __init__(self):
        """
        创建一个中央的PPO agent，用于学习或者在环境中采集的数据
        """
        model = MyModel()
        algorithm = parl.algorithms.PPO(model=model)
        super(LocalAgent, self).__init__(algorithm=algorithm)

    def collect_trajectories(self, env):
        """
        agent和环境交互，收集数据
        :param env:
        :return:
        """
        trajectories = []
        # todo:实现采样的过程
        return trajectories


@parl.remote_class
class RemoteAgent:
    def __init__(self):
        """
        创建一个远程的agent，用于平行计算中采集数据
        """
        self.env = MyEnv()
        # 把本地的agent实例作为自己的属性，用来收集数据
        self.agent = LocalAgent()

    def collect_trajectories(self):
        """
        用agent来采样
        :return:
        """
        return self.agent.collect_trajectories()

    def set_weights(self, weights):
        """
        装载中央的agent的参数
        :param weights:
        :return:
        """
        self.agent.set_weights(weights=weights)


class Learner(object):
    def __init__(self):
        """
        实现平行计算
        """
        self.local_agent = LocalAgent()

    def run_remote_samples(self, weights, trajectories_queue):
        # 创建一个平行计算的agent
        remote_agent = RemoteAgent()
        # load 最新的参数
        remote_agent.set_weights(weights)
        # 收集数据，放到队列中
        trajectories_queue.put(remote_agent.collect_trajectories())

    def step(self):
        cpu_number = 2

        # 用于收集平行actor采样的trajectories
        trajectories_queue = queue.Queue()

        # 发送最新的参数给actor
        local_weights = self.local_agent.get_weights()

        # 开启平行计算的actor
        remote_thread_list = []
        for _ in range(cpu_number):
            remote_thread = threading.Thread(
                target=self.run_remote_samples, args=(local_weights, trajectories_queue))
            remote_thread.setDaemon(True)
            remote_thread.start()

        # 等待数据收集结束
        for t in remote_thread_list:
            t.join()

        # 用收集的数据训练本地的agent
        for _ in range(cpu_number):
            trajectories = trajectories_queue.get()
            self.local_agent.learn(trajectories)


if __name__ == '__main__':
    learner = Learner()
    while True:
        # 不间断的训练
        learner.step()
```

**Comment by TomorrowIsAnOtherDay** [comment]
> 我发现如果@parl.remote_class封装的不是一个基类的话，父类的初始化似乎会出现问题，

请把可以复现这个情况异常的代码贴出来，我们定位确认下问题。

----------------
你的代码我整体看了下，需要注意的一个点是不要重复创建agent。
这个主要问题在于paddle使用的是静态图，反复创建agent会重复构建同样的参数，会引发异常。
这个目前即便用的tensorflow也会有类似的问题。

**Comment by wujiren** [comment]
> > 我发现如果@parl.remote_class封装的不是一个基类的话，父类的初始化似乎会出现问题，
> 
> 请把可以复现这个情况异常的代码贴出来，我们定位确认下问题。

下面是一个可以运行的简单的代码，trajectory返回一个简单的结果，learn只打印一些信息。
```python
import parl
import gym
import threading
import queue
import numpy as np

class Foo:
    def __init__(self):
        super(Foo,self).__init__()
        pass


class MyEnv(gym.Env):
    def __init__(self):
        """
        定义我的环境
        """
        super(MyEnv, self).__init__()


class MyModel(parl.Model):
    def __init__(self, **params):
        """
        定义我的model
        :param params:
        """
        super(MyModel, self).__init__(**params)

    def policy_model(self):
        pass


class LocalAgent(parl.Agent):
    def __init__(self):
        """
        创建一个中央的PPO agent，用于学习或者在环境中采集的数据
        """
        model = MyModel()
        algorithm = parl.algorithms.PPO(model=model, act_dim=1, policy_lr=0.0001, value_lr=0.0001)
        super(LocalAgent, self).__init__(algorithm=algorithm)

    def collect_trajectories(self):
        """
        agent和环境交互，收集数据
        :param env:
        :return:
        """
        trajectories = [{
            'obs': np.array([0]),
            'action': np.array([0]),
            'rewards': np.array([0])
        }]
        # todo:实现采样的过程
        return trajectories

    def build_program(self):
        pass

    def learn(self, t):
        print('learning')


@parl.remote_class
class RemoteAgent:
    def __init__(self):
        """
        创建一个远程的agent，用于平行计算中采集数据
        """
        # super(RemoteAgent,self).__init__()
        self.env = MyEnv()
        # 把本地的agent实例作为自己的属性，用来收集数据
        self.agent = LocalAgent()

    def collect_trajectories(self):
        """
        用agent来采样
        :return:
        """
        return self.agent.collect_trajectories()

    def set_weights(self, weights):
        """
        装载中央的agent的参数
        :param weights:
        :return:
        """
        self.agent.set_weights(weights=weights)


class Learner(object):
    def __init__(self):
        """
        实现平行计算
        """
        self.local_agent = LocalAgent()
        parl.connect('localhost:6006')

    def run_remote_samples(self, weights, trajectories_queue):
        # 创建一个平行计算的agent
        remote_agent = RemoteAgent()
        # load 最新的参数
        remote_agent.set_weights(weights)
        # 收集数据，放到队列中
        trajectories_queue.put(remote_agent.collect_trajectories())

    def step(self):
        cpu_number = 2

        # 用于收集平行actor采样的trajectories
        trajectories_queue = queue.Queue()

        # 发送最新的参数给actor
        local_weights = self.local_agent.get_weights()

        # 开启平行计算的actor
        remote_thread_list = []
        for _ in range(cpu_number):
            remote_thread = threading.Thread(
                target=self.run_remote_samples, args=(local_weights, trajectories_queue))
            remote_thread.setDaemon(True)
            remote_thread.start()

        # 等待数据收集结束
        for t in remote_thread_list:
            t.join()

        # 用收集的数据训练本地的agent
        for _ in range(cpu_number):
            trajectories = trajectories_queue.get()
            print(trajectories)
            self.local_agent.learn(trajectories)


if __name__ == '__main__':
    learner = Learner()
    while True:
        # 不间断的训练
        learner.step()

```
运行结果：
```
[06-04 14:52:02 MainThread @logger.py:224] Argv: 
/Users/jirenwu/opt/anaconda3/envs/tf1/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
[06-04 14:52:04 MainThread @machine_info.py:84] Cannot find available GPU devices, using CPU now.
[06-04 14:52:04 MainThread @machine_info.py:84] Cannot find available GPU devices, using CPU now.
/Users/jirenwu/opt/anaconda3/envs/tf1/lib/python3.7/site-packages/paddle/fluid/executor.py:1093: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
[{'obs': array([0]), 'action': array([0]), 'rewards': array([0])}]
learning
[{'obs': array([0]), 'action': array([0]), 'rewards': array([0])}]
learning
[{'obs': array([0]), 'action': array([0]), 'rewards': array([0])}]
learning
[{'obs': array([0]), 'action': array([0]), 'rewards': array([0])}]
learning
[{'obs': array([0]), 'action': array([0]), 'rewards': array([0])}]
learning
[{'obs': array([0]), 'action': array([0]), 'rewards': array([0])}]
learning
[06-04 14:52:05 Thread-15 @remote_decorator.py:162] WRN No vacant cpu resources at the moment, will try 300 times later.
[06-04 14:52:05 Thread-14 @remote_decorator.py:162] WRN No vacant cpu resources at the moment, will try 300 times later.
```


当我把69行的注释号去掉的时候就会报错
```python
@parl.remote_class
class RemoteAgent:
    def __init__(self):
        """
        创建一个远程的agent，用于平行计算中采集数据
        """
        # super(RemoteAgent,self).__init__()
        self.env = MyEnv()
        # 把本地的agent实例作为自己的属性，用来收集数据
        self.agent = LocalAgent()
```
信息如下：
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/jirenwu/opt/anaconda3/envs/tf1/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/jirenwu/opt/anaconda3/envs/tf1/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jirenwu/workspace/python/frame.py", line 100, in run_remote_samples
    remote_agent = RemoteAgent()
  File "/Users/jirenwu/opt/anaconda3/envs/tf1/lib/python3.7/site-packages/parl/remote/remote_decorator.py", line 127, in __init__
    raise RemoteError('__init__', traceback_str)
parl.remote.exceptions.RemoteError: [PARL remote error when calling function `__init__`]:
super(type, obj): obj must be an instance or subtype of type
```
无论RemoteAgent这个类有没有继承，甚至继承一个自定义的类
```python
@parl.remote_class
class Foo:
    def __init__(self):
        pass


@parl.remote_class
class RemoteAgent(Foo):
    def __init__(self):
        """
        创建一个远程的agent，用于平行计算中采集数据
        """
        super(RemoteAgent,self).__init__()
        self.env = MyEnv()
        # 把本地的agent实例作为自己的属性，用来收集数据
        self.agent = LocalAgent()
```
或者继承parl.Agent
```python
@parl.remote_class
class RemoteAgent(parl.Agent):
    def __init__(self):
        """
        创建一个远程的agent，用于平行计算中采集数据
        """
        super(RemoteAgent,self).__init__()
        self.env = MyEnv()
        # 把本地的agent实例作为自己的属性，用来收集数据
        self.agent = LocalAgent()
```
都会报同样的错

**Comment by TomorrowIsAnOtherDay** [comment]
收到：）感谢反馈，我们这边着手处理下。

**Comment by TomorrowIsAnOtherDay** [comment]
这个问题我们已经本地复现并修复，正在增加最后的测试代码保障可用性，等明天测试完Windows兼容性之后会发一个版本修复这个问题。
再次感谢你的反馈，对我们帮助太大了！

**Comment by wujiren** [comment]
> 这个问题我们已经本地复现并修复，正在增加最后的测试代码保障可用性，等明天测试完Windows兼容性之后会发一个版本修复这个问题。
> 再次感谢你的反馈，对我们帮助太大了！

很高兴能帮上忙，我这边的问题也都解决了，可以运行平行的PPO了，期待你们的下一个版本。

**Comment by TomorrowIsAnOtherDay** [comment]
手动点赞，效率高！
另外我们这边已经在最新的PR里面修复了这个问题（详情见#281），下周会发一个小版本，之后就可以直接在pip 上安装了。

-------------
如果方便的话，还请在您的GitHub账号上开源并行版本的PPO代码，让后来者有个参考：）感谢

**Comment by wujiren** [comment]
> 如果方便的话，还请在您的GitHub账号上开源并行版本的PPO代码，让后来者有个参考：）感谢

这两天在自己的项目上运行了一下，效果不是很好。可能中间还有bug，如果我自己的项目跑成功了，我按照例子改一下吧。希望能炼金成功

**Comment by TomorrowIsAnOtherDay** [comment]
好嘞，祝成功！
