### ISSUE TITLE
在AIStudio里运行parl的QuickStart报错，TypeError: fc() got an unexpected keyword argument 'is_test'

### ISSUE THREAD

**Issue by rical730** [PaddlePaddle/PARL#300]
环境：
parl==1.1.2
paddlepaddle==1.6.2

报错日志
Traceback (most recent call last):
  File "PARL/examples/QuickStart/train.py", line 84, in <module>
    main()
  File "PARL/examples/QuickStart/train.py", line 57, in main
    agent = CartpoleAgent(alg, obs_dim=OBS_DIM, act_dim=ACT_DIM)
  File "/home/aistudio/PARL/examples/QuickStart/cartpole_agent.py", line 25, in __init__
    super(CartpoleAgent, self).__init__(algorithm)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/core/fluid/agent.py", line 87, in __init__
    self.build_program()
  File "/home/aistudio/PARL/examples/QuickStart/cartpole_agent.py", line 34, in build_program
    self.act_prob = self.alg.predict(obs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/algorithms/fluid/policy_gradient.py", line 57, in predict
    return self.model(obs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/core/model_base.py", line 95, in __call__
    return self.forward(*args, **kwargs)
  File "/home/aistudio/PARL/examples/QuickStart/cartpole_model.py", line 28, in forward
    out = self.fc1(obs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/parl/core/fluid/layers/layer_wrappers.py", line 156, in __call__
    is_test=is_test)
TypeError: fc() got an unexpected keyword argument 'is_test'

**Comment by rical730** [comment]
已经解决了，应该是AIstudio上预装的parl版本太低了，重新`pip install -U parl==1.3.1` 一下最新版本的就没问题了
