### ISSUE TITLE
B站强化学习  parl的quickstart例子跑不了

### ISSUE THREAD

**Issue by TronYY** [PaddlePaddle/PARL#590]
B站上科科老师的强化学习教程“世界冠军带你从零实践强化学习”第三节课，让我们安paddlepaddle 1.6.3的版本，可是压根没有这个版本了。安装最新版 但是parl的quickstart例子又跑不了，要求paddlepaddle版本小于2.0

**Comment by TomorrowIsAnOtherDay** [comment]
感谢您的关注，我们建议还是配套对应版本使用的，为了避免不必要的异常。
1.6.3的版本安装可以通过以下命令完成，这个一般是不会有问题的。
```shell
pip install paddlepaddle==1.6.3
```
请把安装错误贴到issue上哈：）

**Comment by TronYY** [comment]
```
(base) E:\PARL\examples\QuickStart>pip install paddlepaddle==1.6.3
ERROR: Could not find a version that satisfies the requirement paddlepaddle==1.6.3
ERROR: No matching distribution found for paddlepaddle==1.6.3

```

**Comment by TomorrowIsAnOtherDay** [comment]
请尝试下这个命令：
``` shell
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple  paddlepaddle=1.6.3
```

**Comment by TronYY** [comment]
> 请尝试下这个命令：
> 
> ```shell
> pip install -i https://pypi.tuna.tsinghua.edu.cn/simple  paddlepaddle=1.6.3
> ```
```
(base) E:\PARL\examples\QuickStart>pip install -i https://pypi.tuna.tsinghua.edu.cn/simple  paddlepaddle==1.6.3
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle==1.6.3
ERROR: No matching distribution found for paddlepaddle==1.6.3

```

**Comment by TronYY** [comment]
> 请尝试下这个命令：
> 
> ```shell
> pip install -i https://pypi.tuna.tsinghua.edu.cn/simple  paddlepaddle=1.6.3
> ```
我其实人在境外

**Comment by TomorrowIsAnOtherDay** [comment]
> 我其实人在境外

https://pypi.org/project/paddlepaddle/1.6.3/#files
建议下载这个里面的文件，然后直接pip 安装即可。

**Comment by TronYY** [comment]
> > 我其实人在境外
> 
> https://pypi.org/project/paddlepaddle/1.6.3/#files
> 建议下载这个里面的文件，然后直接pip 安装即可。

下了这个 paddlepaddle-1.6.3-cp37-cp37m-win_amd64.whl
然后pip install paddlepaddle-1.6.3-cp37-cp37m-win_amd64.whl

为什么仍然提示没有paddle模块呢
```
(python37) E:\PARL\examples>cd QuickStart

(python37) E:\PARL\examples\QuickStart>python train.py
[32m[03-23 22:14:58 MainThread @logger.py:224][0m Argv: train.py
[33m[03-23 22:15:01 MainThread @__init__.py:24][0m [5m[33mWRN[0m No deep learning framework was found, but it's ok for parallel computation.
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    from cartpole_agent import CartpoleAgent
  File "E:\PARL\examples\QuickStart\cartpole_agent.py", line 16, in <module>
    import paddle.fluid as fluid
ModuleNotFoundError: No module named 'paddle'
```

**Comment by TomorrowIsAnOtherDay** [comment]
嗯，这个确实比较奇怪0.0
给两个建议：
1）尝试使用anaconda进行环境管理
2）去paddle核心库那里发issue咨询
PARL这边的团队主要是研发强化学习框架，核心框架paddle的安装和使用是另一个团队负责。
