### ISSUE TITLE
四轮飞行器的代码2.0版本升级出现问题

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/PARL#591]
我在复现飞行器的代码的时候出现了下面的问题：
```
Traceback (most recent call last):
  File "train.py", line 128, in <module>
    train_reward, steps = run_episode(env, agent, rpm)
  File "train.py", line 69, in run_episode
    batch_next_obs, batch_terminal)
  File "/Users/wugaosheng/Documents/baidu/RL/ddpg_quadrotor/quadrotor_agent.py", line 54, in learn
    critic_loss, actor_loss=self.alg.learn(obs, action, reward, next_obs, terminal)
  File "/Users/wugaosheng/anaconda3/lib/python3.7/site-packages/parl/algorithms/paddle/ddpg.py", line 59, in learn
    terminal)
  File "/Users/wugaosheng/anaconda3/lib/python3.7/site-packages/parl/algorithms/paddle/ddpg.py", line 69, in _critic_learn
    next_obs, self.target_model.actor_model(next_obs))
  File "/Users/wugaosheng/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/wugaosheng/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 920, in forward
    raise NotImplementedError
NotImplementedError
```
我的代码为：
```
import parl
from paddle.nn import Linear
# from paddle.fluid import layers
import paddle.nn.functional as F
import paddle.nn as nn
import paddle

class ActorModel(parl.Model):
    def __init__(self, input_shape,act_dim):
        super(ActorModel, self).__init__()
        hidden_dim_1, hidden_dim_2 = 64, 64
        self.fc1 = nn.Linear(input_shape,hidden_dim_1)
        self.fc2=nn.Linear(hidden_dim_1,hidden_dim_2)
        self.fc3=nn.Linear(hidden_dim_2,act_dim)

    def policy(self, obs):
        x = F.tanh(self.fc1(obs))
        x = F.tanh(self.fc2(x))
        return self.fc3(x)

class CriticModel(parl.Model):
    def __init__(self):
        super(CriticModel, self).__init__()
        hidden_dim_1, hidden_dim_2 = 64, 64
        self.fc1 = nn.Linear(64,hidden_dim_1)
        self.f2=nn.Linear(hidden_dim_1,hidden_dim_2)
        self.f3=nn.Linear(hidden_dim_2,1)

    def value(self, obs, act):
        x = F.tanh(self.fc1(obs))
        concat=paddle.concat([x, act], axis=1)
        x = F.tanh(self.fc2(concat))
        Q = F.tanh(self.fc3(x))
        Q=paddle.squeeze(Q, axis=1)
        return Q


class QuadrotorModel(parl.Model):
    def __init__(self, act_dim):
        super(QuadrotorModel, self).__init__()
        self.actor_model = ActorModel(16,act_dim)
        self.critic_model = CriticModel()

    def policy(self, obs):
        return self.actor_model.policy(obs)

    def value(self, obs, act):
        return self.critic_model.value(obs, act)

    def get_actor_params(self):
        return self.actor_model.parameters()

    def get_critic_params(self):
        return self.critic_model.parameters()

```
```
import numpy as np
import parl
# from parl import layers
# from paddle.fluid import layers
# from paddle import fluid
import paddle

class QuadrotorAgent(parl.Agent):
    def __init__(self, algorithm, obs_dim, act_dim=4):
        # assert isinstance(obs_dim, int)
        # assert isinstance(act_dim, int)
        super(QuadrotorAgent, self).__init__(algorithm)
        self.obs_dim = obs_dim
        self.act_dim = act_dim
        self.alg.sync_target(decay=0)

    def sample(self, obs):
        obs = paddle.to_tensor(obs.reshape(1, -1), dtype='float32')
        action, _ = self.alg.sample(obs)
        action_numpy = action.cpu().numpy()[0]
        return action_numpy

    def predict(self, obs):
        obs = paddle.to_tensor(obs.reshape(1, -1), dtype='float32')
        action = self.alg.predict(obs)
        action_numpy = action.cpu().numpy()[0]
        return action_numpy

    def learn(self, obs, action, reward, next_obs, terminal):
        terminal = np.expand_dims(terminal, -1)
        reward = np.expand_dims(reward, -1)

        obs = paddle.to_tensor(obs, dtype='float32')
        action = paddle.to_tensor(action, dtype='float32')
        reward = paddle.to_tensor(reward, dtype='float32')
        next_obs = paddle.to_tensor(next_obs, dtype='float32')
        terminal = paddle.to_tensor(terminal, dtype='float32')
        critic_loss, actor_loss=self.alg.learn(obs, action, reward, next_obs, terminal)
        return critic_loss, actor_loss 

```
```
import os
import numpy as np

import parl
# from parl import layers
# from paddle import fluid
from parl.utils import logger

# from parl.utils import action_mapping  # 将神经网络输出映射到对应的 实际动作取值范围 内
from parl.utils import ReplayMemory  # 经验回放

from rlschool import make_env  # 使用 RLSchool 创建飞行器环境
from quadrotor_model import QuadrotorModel
from quadrotor_agent import QuadrotorAgent
from parl.algorithms import DDPG
from parl.env.continuous_wrappers import ActionMappingWrapper

GAMMA = 0.99  # reward 的衰减因子，一般取 0.9 到 0.999 不等
TAU = 0.001  # target_model 跟 model 同步参数 的 软更新参数
ACTOR_LR = 0.0002  # Actor网络更新的 learning rate
CRITIC_LR = 0.001  # Critic网络更新的 learning rate
MEMORY_SIZE = 1e6  # replay memory的大小，越大越占用内存
MEMORY_WARMUP_SIZE = 1e4  # replay_memory 里需要预存一些经验数据，再从里面sample一个batch的经验让agent去learn
REWARD_SCALE = 0.01  # reward 的缩放因子
BATCH_SIZE = 256  # 每次给agent learn的数据数量，从replay memory随机里sample一批数据出来
TRAIN_TOTAL_STEPS = 1e6  # 总训练步数
TEST_EVERY_STEPS = 1e4  # 每个N步评估一下算法效果，每次评估5个episode求平均reward


def run_episode(env, agent, rpm):
    obs = env.reset()
    total_reward, steps = 0, 0
    while True:
        steps += 1
        batch_obs = np.expand_dims(obs, axis=0)
        action = agent.predict(batch_obs.astype('float32'))
        action = np.squeeze(action)

        # Add exploration noise, and clip to [-1.0, 1.0]
        action = np.clip(np.random.normal(action, 1.0), -1.0, 1.0)
        # action = action_mapping(action, env.action_space.low[0],
        #                         env.action_space.high[0])

        next_obs, reward, done, info = env.step(action)
        rpm.append(obs, action, REWARD_SCALE * reward, next_obs, done)
        # if(rpm.size()>BATCH_SIZE):
        #     print(rpm.sample_batch(BATCH_SIZE))
        #     break
        if rpm.size() > MEMORY_WARMUP_SIZE:
            batch_obs, batch_action, batch_reward, batch_next_obs, batch_terminal = rpm.sample_batch(BATCH_SIZE)
            # print(batch_obs)
            critic_loss, actor_loss  = agent.learn(batch_obs, batch_action, batch_reward,
                                      batch_next_obs, batch_terminal)

        obs = next_obs
        total_reward += reward

        if done:
            break
    return total_reward, steps


# 评估 agent, 跑 5 个episode，总reward求平均
def evaluate(env, agent, render=False):
    eval_reward = []
    for i in range(5):
        obs = env.reset()
        total_reward, steps = 0, 0
        while True:
            batch_obs = np.expand_dims(obs, axis=0)
            action = agent.predict(batch_obs.astype('float32'))
            action = np.squeeze(action)
            action = np.clip(action, -1.0, 1.0)  ## special
            # action = action_mapping(action, env.action_space.low[0],
            #                         env.action_space.high[0])
            # action = np.clip(action, -1.0, 1.0) ## special

            next_obs, reward, done, info = env.step(action)

            obs = next_obs
            total_reward += reward
            steps += 1

            if render:
                env.render()

            if done:
                break
        eval_reward.append(total_reward)
    return np.mean(eval_reward)


# 创建飞行器环境
env = make_env("Quadrotor", task="hovering_control")
# env = ActionMappingWrapper(env)
# env.reset()
obs_dim = env.observation_space.shape[0]
act_dim = env.action_space.shape[0]
logger.info('obs_dim {}, act_dim {}'.format(obs_dim, act_dim))

# 使用parl框架搭建Agent：QuadrotorModel, DDPG, QuadrotorAgent三者嵌套
model = QuadrotorModel(act_dim)
algorithm = DDPG(model, gamma=GAMMA, tau=TAU, actor_lr=ACTOR_LR, critic_lr=CRITIC_LR)
agent = QuadrotorAgent(algorithm, obs_dim, act_dim)

# parl库也为DDPG算法内置了ReplayMemory，可直接从 parl.utils 引入使用
rpm = ReplayMemory(int(MEMORY_SIZE), obs_dim, act_dim)

test_flag = 0
total_steps = 0
while total_steps < TRAIN_TOTAL_STEPS:
    train_reward, steps = run_episode(env, agent, rpm)
    total_steps += steps
    logger.info('Steps: {} Reward: {}'.format(total_steps, train_reward))

    if total_steps // TEST_EVERY_STEPS >= test_flag:
        while total_steps // TEST_EVERY_STEPS >= test_flag:
            test_flag += 1

        evaluate_reward = evaluate(env, agent,True)
        logger.info('Steps {}, Test reward: {}'.format(total_steps,evaluate_reward))

        # 保存模型
        ckpt = 'model_dir/steps_{}.ckpt'.format(total_steps)
        agent.save(ckpt)

```

**Comment by TomorrowIsAnOtherDay** [comment]
感谢你的反馈：）
请把model里面的policy、value函数改成forward。
动态图的文档还在整理中，很抱歉当前对你造成困扰：）
我们预计4月下旬正式发布动态图的全部example以及文档

```python
class ActorModel(parl.Model):
    def __init__(self, input_shape,act_dim):
        super(ActorModel, self).__init__()
        hidden_dim_1, hidden_dim_2 = 64, 64
        self.fc1 = nn.Linear(input_shape,hidden_dim_1)
        self.fc2=nn.Linear(hidden_dim_1,hidden_dim_2)
        self.fc3=nn.Linear(hidden_dim_2,act_dim)

    def policy(self, obs):
        x = F.tanh(self.fc1(obs))
        x = F.tanh(self.fc2(x))
        return self.fc3(x)

class CriticModel(parl.Model):
    def __init__(self):
        super(CriticModel, self).__init__()
        hidden_dim_1, hidden_dim_2 = 64, 64
        self.fc1 = nn.Linear(64,hidden_dim_1)
        self.f2=nn.Linear(hidden_dim_1,hidden_dim_2)
        self.f3=nn.Linear(hidden_dim_2,1)

    def value(self, obs, act):
        x = F.tanh(self.fc1(obs))
        concat=paddle.concat([x, act], axis=1)
        x = F.tanh(self.fc2(concat))
        Q = F.tanh(self.fc3(x))
        Q=paddle.squeeze(Q, axis=1)
        return Q
```

**Comment by TomorrowIsAnOtherDay** [comment]
我看了下最新的文档已经提及这部分，继承model需要写`forward`函数：
https://github.com/PaddlePaddle/PARL/blob/develop/docs/zh_CN/tutorial/module.md#model

**Comment by w5688414** [comment]
@TomorrowIsAnOtherDay  谢谢，问题解决了

**Comment by ly1054** [comment]
> 感谢你的反馈：）
> 请把model里面的policy、value函数改成forward。
> 动态图的文档还在整理中，很抱歉当前对你造成困扰：）
> 我们预计4月下旬正式发布动态图的全部example以及文档
> 
> ```python
> class ActorModel(parl.Model):
>     def __init__(self, input_shape,act_dim):
>         super(ActorModel, self).__init__()
>         hidden_dim_1, hidden_dim_2 = 64, 64
>         self.fc1 = nn.Linear(input_shape,hidden_dim_1)
>         self.fc2=nn.Linear(hidden_dim_1,hidden_dim_2)
>         self.fc3=nn.Linear(hidden_dim_2,act_dim)
> 
>     def policy(self, obs):
>         x = F.tanh(self.fc1(obs))
>         x = F.tanh(self.fc2(x))
>         return self.fc3(x)
> 
> class CriticModel(parl.Model):
>     def __init__(self):
>         super(CriticModel, self).__init__()
>         hidden_dim_1, hidden_dim_2 = 64, 64
>         self.fc1 = nn.Linear(64,hidden_dim_1)
>         self.f2=nn.Linear(hidden_dim_1,hidden_dim_2)
>         self.f3=nn.Linear(hidden_dim_2,1)
> 
>     def value(self, obs, act):
>         x = F.tanh(self.fc1(obs))
>         concat=paddle.concat([x, act], axis=1)
>         x = F.tanh(self.fc2(concat))
>         Q = F.tanh(self.fc3(x))
>         Q=paddle.squeeze(Q, axis=1)
>         return Q
> ```
动态图的example和文档难产了吗？大概啥时候会发？

**Comment by TomorrowIsAnOtherDay** [comment]
今天就发beta版本！
过去的一段时间里，我们开发了如下算法：
DDPG\TD3\SAC\OAC
DQN\A2C\COMA
目前还差IMPALA、MADDPG、PPO 等算法。

**Comment by TomorrowIsAnOtherDay** [comment]
文档已经新增readthedocs的中文版本，感谢各位的支持和关注：）有问题欢迎再提issue。
