### ISSUE TITLE
Error: [WinError 2] 系统找不到指定的文件。: 'D:\\Program\\***\\Experiments\\work\\home\\aistudio\\aistudio\\xparl_actor.py'

### ISSUE THREAD

**Issue by songyuc** [PaddlePaddle/PARL#611]
尊敬的PARL开发者，您好，
我最近在学习使用parl，在运行网上的开源代码时，遇到了这样的问题，（不知道是不是也跟文件路径相关），
错误信息是这样的：
> Exception in thread Thread-6:
Traceback (most recent call last):
  File "F:\Users\songyuc\anaconda3\envs\conda-paddle\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "F:\Users\songyuc\anaconda3\envs\conda-paddle\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:/Program/***/Experiments/work/home/aistudio/aistudio/train.py", line 93, in run_remote_sample
    remote_actor = Actor(self.config)
  File "F:\Users\songyuc\anaconda3\envs\conda-paddle\lib\site-packages\parl\remote\proxy_wrapper.py", line 64, in __init__
    self._xparl_remote_wrapper_obj = remote_wrapper(*args, **kwargs)
  File "F:\Users\songyuc\anaconda3\envs\conda-paddle\lib\site-packages\parl\remote\remote_wrapper.py", line 122, in __init__
    raise RemoteError('__init__', traceback_str)
parl.remote.exceptions.RemoteError: [PARL remote error when calling function `__init__`]:
[WinError 2] 系统找不到指定的文件。: 'D:\\Program\\***\\Experiments\\work\\home\\aistudio\\aistudio\\xparl_actor.py'
traceback:
Traceback (most recent call last):
  File "f:\users\songyuc\anaconda3\envs\conda-paddle\lib\site-packages\parl\remote\job.py", line 301, in wait_for_connection
    cls = load_remote_class(file_name, class_name, end_of_file,
  File "f:\users\songyuc\anaconda3\envs\conda-paddle\lib\site-packages\parl\remote\utils.py", line 91, in load_remote_class
    os.remove(tmp_file_name)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'D:\\Program\\***\\Experiments\\work\\home\\aistudio\\aistudio\\xparl_actor.py'

期待你的回复和解答！

**Comment by TomorrowIsAnOtherDay** [comment]
问下你运行的源码能贴下吗？
请提供下相关的代码、运行方式以及运行环境，方便我们这边复现问题。

**Comment by songyuc** [comment]
@TomorrowIsAnOtherDay ，你好，https://aistudio.baidu.com/aistudio/projectdetail/1772212
操作系统：Win10
IDE：PyCharm

**Comment by TomorrowIsAnOtherDay** [comment]
运行方式可以提供下吗？怎么复现你的错误呢？

**Comment by songyuc** [comment]
@TomorrowIsAnOtherDay ，我看看，
就是，
1. 首先把代码下载下来，然后用PyCharm打开
2. 在`arknights.py`中更改图像文件夹的路径`IMAGE_DIR`，我这里使用的是绝对路径，例如：`"D:\\Program\\***\\Experiments\\work\\home\\aistudio\\aistudio\\simulator\\images\\"`，在运行时，需要改成相应的绝对路径，例如：`abs_repo_path\\work\\simulator\\images\\`；这样之后，应该是可以读取图像文件夹了；
3. 修改Linux路径连接符`/`，由于此项目是在Linux系统中测试的，在Win10系统应该还需要修改连接符，在IDE中搜索`'/'`，并修改为`"\\"`；则可以解决连接符不同的问题；
4. 启动master，`xparl start --port 8010` 
5. 在PyCharm中点击**运行**按钮，则会出错；

您看还有什么需要补充的，

**Comment by TomorrowIsAnOtherDay** [comment]
了解了：）十分感谢你的配合。
我们下一个工作日复现下这个问题，目前手头上没有Windows机器，得要等一工作日IT部门上班才可以借到机器。

**Comment by zenghsh3** [comment]
你好，我们在 #614 PR解决了你提到的问题，你可以尝试下载该PR进行测试（fix_bug分支）。

**Comment by TomorrowIsAnOtherDay** [comment]
目前已经修复问题合并到主干，请参考我们的[文档](https://github.com/PaddlePaddle/PARL/blob/develop/docs/zh_CN/Overview.md#%E5%AE%89%E8%A3%85-1)直接安装最新版本的代码。
