### ISSUE TITLE
AttributeError: 'AtariModel' object has no attribute 'value'

### ISSUE THREAD

**Issue by 237035848** [PaddlePaddle/PARL#677]
examples下的DQN_variant 使用DDQN报错
readme推荐环境是
+ [paddlepaddle>=2.0.0](https://github.com/PaddlePaddle/Paddle)
+ [parl>=2.0.1](https://github.com/PaddlePaddle/PARL)
+ gym==0.18.0
+ tqdm
+ atari-py==0.2.6
我的环境是
+ [paddlepaddle>=2.0.0](https://github.com/PaddlePaddle/Paddle)
+ [parl =2.1.1](https://github.com/PaddlePaddle/PARL)
+ gym==0.18.3
+ tqdm
+ atari-py==0.2.6

**Comment by TomorrowIsAnOtherDay** [comment]
hello，感谢您的反馈。
麻烦贴一下相应的错误提示。

**Comment by 237035848** [comment]
Traceback (most recent call last):
  File "C:/Users/YLJ/Desktop/Program of DRL/PARL-develop/examples/DQN_variant/train.py", line 213, in <module>
    main()
  File "C:/Users/YLJ/Desktop/Program of DRL/PARL-develop/examples/DQN_variant/train.py", line 127, in main
    total_reward, steps, _ = run_train_episode(agent, env, rpm)
  File "C:/Users/YLJ/Desktop/Program of DRL/PARL-develop/examples/DQN_variant/train.py", line 72, in run_train_episode
    train_loss = agent.learn(batch_obs, batch_action, batch_reward,
  File "C:\Users\YLJ\Desktop\Program of DRL\PARL-develop\examples\DQN_variant\atari_agent.py", line 114, in learn
    loss = self.alg.learn(obs, act, reward, next_obs, terminal)
  File "C:\Users\YLJ\Desktop\Program of DRL\PARL-develop\parl\algorithms\paddle\ddqn.py", line 65, in learn
    greedy_actions = self.model.value(next_obs).argmax(1)
  File "D:\Anaconda3\envs\PARL\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1050, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'AtariModel' object has no attribute 'value'

**Comment by TomorrowIsAnOtherDay** [comment]
这是我们昨天刚修复的bug(#675)，原因是统一model的接口时候忽略了ddqn这个算法，现在马上发版本修复这个问题。
十分感谢您的反馈。
建议在parl根目录下使用`pip install .` 的方式安装最新版本parl先使用，我们立刻启动发版流程。

**Comment by 237035848** [comment]
谢谢您！
