### ISSUE TITLE
强化学习营第3节DQN训练报错

### ISSUE THREAD

**Issue by yecai123** [PaddlePaddle/PARL#796]
下载的源代码，运行train时出现了以下的报错。求解！

报错提示：

E:\anaconda\python.exe "F:/Pycharm Files/examples/DRL-parl-lessons/lessons3-DQN/train.py"

[02-26 17:33:33 MainThread @logger.py:242] Argv: F:/Pycharm Files/examples/DRL-parl-lessons/lessons3-DQN/train.py
E:\anaconda\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
[02-26 17:33:35 MainThread @utils.py:73] paddlepaddle version: 2.2.2.
Traceback (most recent call last):
  File "F:\Pycharm Files\examples\DRL-parl-lessons\lessons3-DQN\train.py", line 132, in <module>
    main()
  File "F:\Pycharm Files\examples\DRL-parl-lessons\lessons3-DQN\train.py", line 94, in main
    model = Model(act_dim=action_dim)
  File "F:\Pycharm Files\examples\DRL-parl-lessons\lessons3-DQN\model.py", line 26, in __init__
    self.fc1 = layers.fc(size=hid1_size, act='relu')
TypeError: fc() missing 1 required positional argument: 'input'

**Comment by rical730** [comment]
这个问题一般是版本安装不对，你可以检查一下自己的环境是不是 paddlepaddle==1.6.3, parl==1.4, gym==0.18.0 哈~

```
python -m pip list | grep paddlepaddle
python -m pip list | grep parl
python -m pip list | grep gym
```

**Comment by yecai123** [comment]
> 这个问题一般是版本安装不对，你可以检查一下自己的环境是不是 paddlepaddle==1.6.3, parl==1.4, gym==0.18.0 哈~
> 
> ```
> python -m pip list | grep paddlepaddle
> python -m pip list | grep parl
> python -m pip list | grep gym
> ```

谢谢！是的，我安装的最新版的所以很多地方都有报错。我用了新版的代码之后就可以跑通了

**Comment by rical730** [comment]
赞~
