### ISSUE TITLE
运行QuickTrain报错

### ISSUE THREAD

**Issue by leshui1991** [PaddlePaddle/PARL#801]
从QuickTrain的69行
def main():
    env = gym.make('CartPole-v0')
最终定位到gym里
  File "C:\Users\Admin\anaconda3\lib\site-packages\gym\envs\classic_control\cartpole.py", line 10, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'
请问是gym的版本问题吗，gym是0.22.0

完整信息如下
PS C:\Users\Admin>
                 > & conda run -n base --no-capture-output --live-stream python "d:/OneDrive - chziqi/Develop/Reinforcement Learning/PARL-develop/examples/QuickStart/train.py"

[03-07 10:38:00 MainThread @logger.py:242] Argv: d:/OneDrive - chziqi/Develop/Reinforcement Learning/PARL-develop/examples/QuickStart/train.py
[03-07 10:38:02 MainThread @utils.py:73] paddlepaddle version: 2.2.2.
Traceback (most recent call last):
  File "d:/OneDrive - chziqi/Develop/Reinforcement Learning/PARL-develop/examples/QuickStart/train.py", line 108, in <module>
    main()
  File "d:/OneDrive - chziqi/Develop/Reinforcement Learning/PARL-develop/examples/QuickStart/train.py", line 70, in main
    env = gym.make('CartPole-v1')
  File "C:\Users\Admin\anaconda3\lib\site-packages\gym\envs\registration.py", line 676, in make
    return registry.make(id, **kwargs)
  File "C:\Users\Admin\anaconda3\lib\site-packages\gym\envs\registration.py", line 520, in make
    return spec.make(**kwargs)
  File "C:\Users\Admin\anaconda3\lib\site-packages\gym\envs\registration.py", line 139, in make
    cls = load(self.entry_point)
  File "C:\Users\Admin\anaconda3\lib\site-packages\gym\envs\registration.py", line 55, in load
    mod = importlib.import_module(mod_name)
  File "C:\Users\Admin\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Admin\anaconda3\lib\site-packages\gym\envs\classic_control\__init__.py", line 1, in <module>
    from gym.envs.classic_control.cartpole import CartPoleEnv
  File "C:\Users\Admin\anaconda3\lib\site-packages\gym\envs\classic_control\cartpole.py", line 10, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', 'd:/OneDrive - chziqi/Develop/Reinforcement Learning/PARL-develop/examples/QuickStart/train.py']' command failed.  (See above for error)

**Comment by zenghsh3** [comment]
你好，错误应该是找不到pygame库，可以尝试`pip install pygame`
