### ISSUE TITLE
第四课PG作业Pong报错：WinError 126找不到指定模块

### ISSUE THREAD

**Issue by ppdes** [PaddlePaddle/PARL#817]
在进行第四课作业（Pong-v0那个环境）时出现了以下报错：
Traceback (most recent call last):
  File "M:/LearnbySelf/reinforce learning/PARL/examples/tutorials/lesson4/policy_gradient_pong/train.py", line 125, in <module>
    main()
  File "M:/LearnbySelf/reinforce learning/PARL/examples/tutorials/lesson4/policy_gradient_pong/train.py", line 87, in main
    env = gym.make('Pong-v0')
  File "M:\LearnbySelf\reinforce learning\venv\lib\site-packages\gym\envs\registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "M:\LearnbySelf\reinforce learning\venv\lib\site-packages\gym\envs\registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "M:\LearnbySelf\reinforce learning\venv\lib\site-packages\gym\envs\registration.py", line 59, in make
    cls = load(self.entry_point)
  File "M:\LearnbySelf\reinforce learning\venv\lib\site-packages\gym\envs\registration.py", line 18, in load
    mod = importlib.import_module(mod_name)
  File "S:\Python3.6.6\3.6.6\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "M:\LearnbySelf\reinforce learning\venv\lib\site-packages\gym\envs\atari\__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "M:\LearnbySelf\reinforce learning\venv\lib\site-packages\gym\envs\atari\atari_env.py", line 9, in <module>
    import atari_py
  File "M:\LearnbySelf\reinforce learning\venv\lib\site-packages\atari_py\__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "M:\LearnbySelf\reinforce learning\venv\lib\site-packages\atari_py\ale_python_interface.py", line 18, in <module>
    'ale_interface/ale_c.dll'))
  File "S:\Python3.6.6\3.6.6\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "S:\Python3.6.6\3.6.6\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

版本：
atari-py ==0.3.0
gym == 0.18.0
paddlepaddle == 1.8.5
parl == 1.4.1

第四课源代码是没有问题可以跑的。然后我进行过的操作是pip install 了 atari-py，然后在第四课代码基础上修改了环境以及跟着视频修改了calc_reward_to_go函数，但是无法运行，报错如上，感觉大概率是代码问题，但是可能自己没有完全理解课堂内容，也不太敢动其他部分。 希望老师指点，谢谢谢谢！！！

**Comment by rical730** [comment]
看日志是环境的代码问题，因为在env = gym.make('Pong-v0')这一步就报错了，接下去的报错日志均是环境相关的。

建议你可以先debug一下自己的环境代码，确保能够通过env = gym.make('Pong-v0')创建自己的环境，且使用env.step()API 也不会报错，再来修改调试算法相关的代码。

**Comment by ppdes** [comment]
回来记录一下，问题已解决，是atari版本问题，之前install的是atati-py== 0.3.0 ，会报这个错误，之后修改为 0.1.15就没有问题了……
顺带一提，前几节课的paddlepaddle，parl的版本似乎都不能作用于后面的课程，后面课程的高版本也不能与前面兼容，有点怪的……（不过第四课作业最后还是看老师给到的代码才能完全跑通，但是一下子还是看不懂，还是继续努力吧……）

**Comment by TomorrowIsAnOtherDay** [comment]
感谢你的反馈！ 我们会新增下atari-py的版本说明（这个锅其实PARL不背，主要是atari-py的版本向下兼容做的不好）

第二个问题，parl的版本说明按照[这里](https://github.com/PaddlePaddle/PARL/tree/develop/examples/tutorials#%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96%E6%B3%A8%E6%84%8F%E8%AF%B7%E5%8A%A1%E5%BF%85%E5%AE%89%E8%A3%85%E5%AF%B9%E5%BA%94%E7%9A%84%E7%89%88%E6%9C%AC) 应该没问题？我们之前测试过了的，并且没看到其他学员反馈版本问题。

**Comment by ppdes** [comment]
第二个问题按照代码给的版本号确实没问题啦，本来是想说每换一个项目版本都得换怪麻烦的来着（挠头），代码按照正确版本都能跑通的
然后又测试了一下atari-py，确认了是其版本问题（兼容做的确实不太行啊……），感谢各位老师的解答啦！！

**Comment by TomorrowIsAnOtherDay** [comment]
不客气，PARL正在持续迭代研发中，欢迎star关注我们的项目，以便及时获取PARL项目的最新研发进展

**Comment by rical730** [comment]
验证了一下，确实atari-py从 0.2.7版本开始就会报上述错误了，当时课程代码开发时用的是atari-py==0.2.6，使用该版本或之前的版本是没问题的，已经在readme中新增atari-py的版本说明，以防止开发者运行代码时再踩坑。

**Comment by ppdes** [comment]
> 验证了一下，确实atari-py从 0.2.7版本开始就会报上述错误了，当时课程代码开发时用的是atari==0.2.6，使用该版本或之前的版本是没问题的，已经在readme中新增atari-py的版本说明，以防止开发者运行代码时再踩坑。

好的，辛苦啦

**Comment by zl-yang** [comment]
我的环境是paddlepaddle-gpu==2.2.2
parl==2.0.3
gym==0.18.0
atari-py==0.2.6
但是也报楼主上面的错[哭]，还有好心人来解答一下我的疑惑嘛，不胜感激！
