### ISSUE TITLE
请问能否将本地主机的CPU资源加入到远程服务器上启动的Xparl集群？

### ISSUE THREAD

**Issue by zhujhz** [PaddlePaddle/PARL#857]
当我在服务器运行 xparl start --port 6006 启动一个集群后，我希望将本地的CPU加入到这个集群中，因此我在本地运行 xparl connect --address severaddress:6006，但是这样会导致报错

Traceback (most recent call last):
  File "/user/zhujianhang/.conda/envs/ijcaibaseparl/bin/xparl", line 8, in <module>
    sys.exit(main())
  File "/user/zhujianhang/.conda/envs/ijcaibaseparl/lib/python3.9/site-packages/parl/remote/scripts.py", line 374, in main
    return cli()
  File "/user/zhujianhang/.conda/envs/ijcaibaseparl/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/user/zhujianhang/.conda/envs/ijcaibaseparl/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/user/zhujianhang/.conda/envs/ijcaibaseparl/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/user/zhujianhang/.conda/envs/ijcaibaseparl/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/user/zhujianhang/.conda/envs/ijcaibaseparl/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/user/zhujianhang/.conda/envs/ijcaibaseparl/lib/python3.9/site-packages/parl/remote/scripts.py", line 281, in start_worker
    raise Exception("Worker can not connect to the master node, " +
Exception: Worker can not connect to the master node, please check if the input address severaddress:6006 is correct.

请问我该如何实现将本地主机的CPU资源加入到在远程服务器上启动的集群呢？

**Comment by TomorrowIsAnOtherDay** [comment]
你这个severaddress填写正确了吗？你在这个机器上能ping通master节点所在的机器吗？
