### ISSUE TITLE
PARL/examples/DDPG  Mujoco应用失败

### ISSUE THREAD

**Issue by Woodeeer** [PaddlePaddle/PARL#859]
[05-06 15:23:17 MainThread @utils.py:73] paddlepaddle version: 2.2.2.
[2022-05-06 15:23:18,441] Making new env: HalfCheetah-v1
D:\Anaconda3\envs\TheReinforceLearning\lib\site-packages\gym\envs\registration.py:17: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Traceback (most recent call last):
  File "D:/pythonTRLProject/VideoProject/DDPG_Mujoco/train.py", line 136, in <module>
    main()
  File "D:/pythonTRLProject/VideoProject/DDPG_Mujoco/train.py", line 76, in main
    env = gym.make(args.env)
  File "D:\Anaconda3\envs\TheReinforceLearning\lib\site-packages\gym\envs\registration.py", line 161, in make
    return registry.make(id)
  File "D:\Anaconda3\envs\TheReinforceLearning\lib\site-packages\gym\envs\registration.py", line 119, in make
    env = spec.make()
  File "D:\Anaconda3\envs\TheReinforceLearning\lib\site-packages\gym\envs\registration.py", line 85, in make
    cls = load(self._entry_point)
  File "D:\Anaconda3\envs\TheReinforceLearning\lib\site-packages\gym\envs\registration.py", line 17, in load
    result = entry_point.load(False)
  File "D:\Anaconda3\envs\TheReinforceLearning\lib\site-packages\pkg_resources\__init__.py", line 2458, in load
    return self.resolve()
  File "D:\Anaconda3\envs\TheReinforceLearning\lib\site-packages\pkg_resources\__init__.py", line 2464, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\Anaconda3\envs\TheReinforceLearning\lib\site-packages\gym\envs\mujoco\__init__.py", line 1, in <module>
    from gym.envs.mujoco.mujoco_env import MujocoEnv
  File "D:\Anaconda3\envs\TheReinforceLearning\lib\site-packages\gym\envs\mujoco\mujoco_env.py", line 11, in <module>
    import mujoco_py
  File "D:\Anaconda3\envs\TheReinforceLearning\lib\site-packages\mujoco_py\__init__.py", line 2, in <module>
    init_config()
  File "D:\Anaconda3\envs\TheReinforceLearning\lib\site-packages\mujoco_py\config.py", line 33, in init_config
[05-06 15:23:18 MainThread @train.py:71] ------------------ DDPG ---------------------
[05-06 15:23:18 MainThread @train.py:72] Env: HalfCheetah-v1, Seed: 0
[05-06 15:23:18 MainThread @train.py:73] ---------------------------------------------
    raise error.MujocoDependencyError('To use MuJoCo, you need to either populate ~/.mujoco/mjkey.txt and ~/.mujoco/mjpro131, or set the MUJOCO_PY_MJKEY_PATH and MUJOCO_PY_MJPRO_PATH environment variables appropriately. Follow the instructions on https://github.com/openai/mujoco-py for where to obtain these.')
mujoco_py.error.MujocoDependencyError: To use MuJoCo, you need to either populate ~/.mujoco/mjkey.txt and ~/.mujoco/mjpro131, or set the MUJOCO_PY_MJKEY_PATH and MUJOCO_PY_MJPRO_PATH environment variables appropriately. Follow the instructions on https://github.com/openai/mujoco-py for where to obtain these.

**Comment by Woodeeer** [comment]
已经解决了这个问题，如果有需要的可以看这篇文章https://www.jianshu.com/p/a0a87ba6ef12

**Comment by TomorrowIsAnOtherDay** [comment]
点赞👍

2022年5月6日 下午5:13，Woodeeer ***@***.******@***.***>> 写道：



已经解决了这个问题，如果有需要的可以看这篇文章https://www.jianshu.com/p/a0a87ba6ef12<https://mailshield.baidu.com/check?q=%2b8tcM4GFOa5FITSU0Itv4FygAB%2fNaSmRR%2fc8M%2fOJKPh1HqQEcGc8LOFugrU%3d>
