### ISSUE TITLE
parl集成的tensorboardX无法下载csv和json数据

### ISSUE THREAD

**Issue by amocken** [PaddlePaddle/PARL#868]
![image](https://user-images.githubusercontent.com/48198083/167990116-83f50d08-5397-4431-9f33-021156b25cc0.png)
然后执行tensorboard的命令行上会显示这样的错误
E0512 11:43:33.712606  5920 _internal.py:225] Error on request:
Traceback (most recent call last):
  File "D:\Programs\miniconda3\envs\python3_8\Lib\site-packages\werkzeug\serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "D:\Programs\miniconda3\envs\python3_8\Lib\site-packages\werkzeug\serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "D:\Programs\miniconda3\envs\python3_8\Lib\site-packages\tensorboard\backend\application.py", line 351, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "D:\Programs\miniconda3\envs\python3_8\Lib\site-packages\werkzeug\wrappers\request.py", line 206, in application
    resp = f(*args[:-2] + (request,))
  File "D:\Programs\miniconda3\envs\python3_8\Lib\site-packages\tensorboard\plugins\scalar\scalars_plugin.py", line 205, in scalars_route
    (body, mime_type) = self.scalars_impl(tag, run, experiment, output_format)
  File "D:\Programs\miniconda3\envs\python3_8\Lib\site-packages\tensorboard\plugins\scalar\scalars_plugin.py", line 163, in scalars_impl
    tensor_events = self._multiplexer.Tensors(run, tag)
  File "D:\Programs\miniconda3\envs\python3_8\Lib\site-packages\tensorboard\backend\event_processing\plugin_event_multiplexer.py", line 405, in Tensors
    accumulator = self.GetAccumulator(run)
  File "D:\Programs\miniconda3\envs\python3_8\Lib\site-packages\tensorboard\backend\event_processing\plugin_event_multiplexer.py", line 481, in GetAccumulator
    return self._accumulators[run]
KeyError: 'undefined'

parl版本：2.0.3
Python版本：3.8
飞桨版本：2.1.0
Windows 11

**Comment by TomorrowIsAnOtherDay** [comment]
hello，你可以尝试下直接运行这里的代码看看能否正常下载：
https://github.com/PaddlePaddle/PARL/blob/develop/docs/zh_CN/tutorial/summary.md#%E6%8A%98%E7%BA%BF%E5%9B%BE%E6%8E%A5%E5%8F%A3add_scalar

**Comment by amocken** [comment]
> hello，你可以尝试下直接运行这里的代码看看能否正常下载： https://github.com/PaddlePaddle/PARL/blob/develop/docs/zh_CN/tutorial/summary.md#%E6%8A%98%E7%BA%BF%E5%9B%BE%E6%8E%A5%E5%8F%A3add_scalar

还是不行

**Comment by TomorrowIsAnOtherDay** [comment]
你是否本地有挂载代理呢？

**Comment by amocken** [comment]
> 你是否本地有挂载代理呢？

没有

**Comment by TomorrowIsAnOtherDay** [comment]
我感觉你的问题出现在tensorboardX上，你可以试试直接使用tensorboardX的原生API看看，如果还是有问题建议去tensorboardX官方仓库解答（我们确实解答不了），如果问题消失了说明是parl的封装问题（我猜概率不高）。

**Comment by TomorrowIsAnOtherDay** [comment]
https://github.com/lanpa/tensorboardX
