### ISSUE TITLE
最近更新的第四课作业的动态图，环境配置问题

### ISSUE THREAD

**Issue by zl-yang** [PaddlePaddle/PARL#895]
https://github.com/PaddlePaddle/PARL/blob/develop/examples/tutorials/parl2_dygraph/README.md
我的环境是：paddlepaddle-gpu==2.2.0；parl==2.0.3；gym==0.18.0；atari-py==0.2.6
仍然报错：OSError: [WinError 126] 找不到指定的模块。
除了这个，之前的parl2_dygraph都可顺利跑通

=====================================
在此先谢谢好心人了！！！

**Comment by zl-yang** [comment]
emmmm我试过了，除了lesson4的homework跑不起来，其余都跑起来了……

**Comment by TomorrowIsAnOtherDay** [comment]
hello，感谢反馈：）
请提供下你的系统信息。

**Comment by zl-yang** [comment]
> hello，感谢反馈：） 请提供下你的系统信息。
是anaconda里的虚拟环境，使用pycharm运行的。
==============================================
D:\apps\Anaconda3\envs\parl\python.exe E:/学习资料/PARL-develop/PARL-develop/examples/tutorials/parl2_dygraph/lesson4/homework/policy_gradient_pong/train.py
[06-14 18:59:56 MainThread @logger.py:242] Argv: E:/学习资料/PARL-develop/PARL-develop/examples/tutorials/parl2_dygraph/lesson4/homework/policy_gradient_pong/train.py
D:\apps\Anaconda3\envs\parl\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
D:\apps\Anaconda3\envs\parl\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
D:\apps\Anaconda3\envs\parl\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
D:\apps\Anaconda3\envs\parl\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
D:\apps\Anaconda3\envs\parl\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
D:\apps\Anaconda3\envs\parl\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
[06-14 19:00:01 MainThread @utils.py:73] paddlepaddle version: 2.2.0.
Traceback (most recent call last):
  File "E:/学习资料/PARL-develop/PARL-develop/examples/tutorials/parl2_dygraph/lesson4/homework/policy_gradient_pong/train.py", line 136, in <module>
    main()
  File "E:/学习资料/PARL-develop/PARL-develop/examples/tutorials/parl2_dygraph/lesson4/homework/policy_gradient_pong/train.py", line 99, in main
    env = gym.make('Pong-v0')
  File "D:\apps\Anaconda3\envs\parl\lib\site-packages\gym\envs\registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "D:\apps\Anaconda3\envs\parl\lib\site-packages\gym\envs\registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "D:\apps\Anaconda3\envs\parl\lib\site-packages\gym\envs\registration.py", line 59, in make
    cls = load(self.entry_point)
  File "D:\apps\Anaconda3\envs\parl\lib\site-packages\gym\envs\registration.py", line 18, in load
    mod = importlib.import_module(mod_name)
  File "D:\apps\Anaconda3\envs\parl\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\apps\Anaconda3\envs\parl\lib\site-packages\gym\envs\atari\__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "D:\apps\Anaconda3\envs\parl\lib\site-packages\gym\envs\atari\atari_env.py", line 9, in <module>
    import atari_py
  File "D:\apps\Anaconda3\envs\parl\lib\site-packages\atari_py\__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "D:\apps\Anaconda3\envs\parl\lib\site-packages\atari_py\ale_python_interface.py", line 18, in <module>
    'ale_interface/ale_c.dll'))
  File "D:\apps\Anaconda3\envs\parl\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "D:\apps\Anaconda3\envs\parl\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

Process finished with exit code 1

**Comment by cnhemiya** [comment]
可以跑起来，paddle是gpu版本

- import paddle;paddle.__version__;
- '2.3.0'
- import parl;parl.__version__
- '2.0.4'
- import gym;gym.__version__;
- '0.18.0'

把前面的 assert 注释掉

**Comment by SpikeRuan** [comment]
> emmmm我试过了，除了lesson4的homework跑不起来，其余都跑起来了……

想问下dqn那个怎么跑起来的，我的报错 ImportError: cannot import name 'layers' from 'parl'

**Comment by zl-yang** [comment]
找一下说明文档readme里面有版本号，应该是parl版本问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月12日 19:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PARL] 最近更新的第四课作业的动态图，环境配置问题 (Issue #895) |

emmmm我试过了，除了lesson4的homework跑不起来，其余都跑起来了……

想问下dqn那个怎么跑起来的，我的报错 ImportError: cannot import name 'layers' from 'parl'

**Comment by ZhangzrJerry** [comment]
I've got the same problem with 
paddlecpu - 2.3.2
parl - 2.0.5

**Comment by ZhangzrJerry** [comment]
事实上我有很多例程都跑不起来，需要进行部分修改，这可能是我与课程发布时的py包版本不同导致的
