### ISSUE TITLE
在使用xparl过程中，无法使用tensorboard

### ISSUE THREAD

**Issue by HAOGUOKAI** [PaddlePaddle/PARL#905]
在xparl运行过程中，无法使用anaconda打开tensorboard图。出现如下错误：
(base) C:\Users\HGK>tensorboard --logdir=E:\\football\QMIX6\log_path\2022-06-13-22-59-36events
Traceback (most recent call last):
  File "C:\Users\HGK\Anaconda3\Scripts\tensorboard-script.py", line 9, in <module>
    sys.exit(run_main())
  File "C:\Users\HGK\Anaconda3\lib\site-packages\tensorboard\main.py", line 46, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "C:\Users\HGK\Anaconda3\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\HGK\Anaconda3\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "C:\Users\HGK\Anaconda3\lib\site-packages\tensorboard\program.py", line 276, in main
    return runner(self.flags) or 0
  File "C:\Users\HGK\Anaconda3\lib\site-packages\tensorboard\program.py", line 292, in _run_serve_subcommand
    server = self._make_server()
  File "C:\Users\HGK\Anaconda3\lib\site-packages\tensorboard\program.py", line 474, in _make_server
    return self.server_class(app, self.flags)
  File "C:\Users\HGK\Anaconda3\lib\site-packages\tensorboard\program.py", line 638, in init
    return cls(wsgi_app=wsgi_app, flags=subflags)
  File "C:\Users\HGK\Anaconda3\lib\site-packages\tensorboard\program.py", line 687, in __init__
    host, port, wsgi_app, _WSGIRequestHandler
  File "C:\Users\HGK\Anaconda3\lib\site-packages\werkzeug\serving.py", line 699, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "C:\Users\HGK\Anaconda3\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Users\HGK\Anaconda3\lib\site-packages\tensorboard\program.py", line 805, in server_bind
    super(WerkzeugServer, self).server_bind()
  File "C:\Users\HGK\Anaconda3\lib\http\server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "C:\Users\HGK\Anaconda3\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

**Comment by TomorrowIsAnOtherDay** [comment]
“在xparl运行过程中，无法使用anaconda打开tensorboard图”
也就是说，把xparl关闭之后，tensorboard就可以正常打开了吗？

**Comment by HAOGUOKAI** [comment]
> “在xparl运行过程中，无法使用anaconda打开tensorboard图” 也就是说，把xparl关闭之后，tensorboard就可以正常打开了吗？

是的，如果是在与程序运行不同的环境中调用tensorboard，就会出现上述问题，但是如果在与程序运行相同的环境中调用tensorboard，就会出现以下报错：

(ray) C:\Users\HGK>tensorboard --logdir=E:\桌面图标\临时\及第\football\QMIX6\log_path\2022-06-13-22-59-36events
TensorFlow installation not found - running with reduced feature set.
Traceback (most recent call last):
  File "D:\DevTools\Anaconda3-5.2.0\envs\ray\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\DevTools\Anaconda3-5.2.0\envs\ray\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\DevTools\Anaconda3-5.2.0\envs\ray\Scripts\tensorboard.exe\__main__.py", line 7, in <module>
  File "D:\DevTools\Anaconda3-5.2.0\envs\ray\lib\site-packages\tensorboard\main.py", line 46, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "D:\DevTools\Anaconda3-5.2.0\envs\ray\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "D:\DevTools\Anaconda3-5.2.0\envs\ray\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "D:\DevTools\Anaconda3-5.2.0\envs\ray\lib\site-packages\tensorboard\program.py", line 276, in main
    return runner(self.flags) or 0
  File "D:\DevTools\Anaconda3-5.2.0\envs\ray\lib\site-packages\tensorboard\program.py", line 292, in _run_serve_subcommand
    server = self._make_server()
  File "D:\DevTools\Anaconda3-5.2.0\envs\ray\lib\site-packages\tensorboard\program.py", line 467, in _make_server
    app = application.TensorBoardWSGIApp(
  File "D:\DevTools\Anaconda3-5.2.0\envs\ray\lib\site-packages\tensorboard\backend\application.py", line 139, in TensorBoardWSGIApp
    return TensorBoardWSGI(
  File "D:\DevTools\Anaconda3-5.2.0\envs\ray\lib\site-packages\tensorboard\backend\application.py", line 252, in __init__
    raise ValueError(
ValueError: Duplicate plugins for name projector

**Comment by TomorrowIsAnOtherDay** [comment]
这个看着像是tensorboard 和你已经安装的包有冲突了，我建议可以试试使用anaconda 重新创建一个环境，只安装PARL，然后调用tensorboard试试看。
