### ISSUE TITLE
在跑四轴飞行器的project时如果把render设为true出现AttributeError: 'ColorVisuals' object has no attribute 'crc'

### ISSUE THREAD

**Issue by Marverlises** [PaddlePaddle/PARL#977]
在跑四轴飞行器的project时如果把render设为true出现AttributeError: 'ColorVisuals' object has no attribute 'crc'，有人知道该怎么解决吗，谢谢!

**Comment by Marverlises** [comment]
D:\Anaconda\envs\paddlepaddle\lib\site-packages\trimesh\parent.py:94: DeprecationWarning: `geometry.md5()` is deprecated and will be removed in October 2023: replace with `geometry.__hash__()` or `hash(geometry)`
  DeprecationWarning)
Traceback (most recent call last):
  File "D:/Desktop/PARL_develop_examples_tutorials (1)/examples/parl2_dygraph_new/lesson5/homework/ddpg_quadrotor/train.py", line 184, in <module>
    main()
  File "D:/Desktop/PARL_develop_examples_tutorials (1)/examples/parl2_dygraph_new/lesson5/homework/ddpg_quadrotor/train.py", line 163, in main
    agent, env, EVAL_EPISODES, render=True)
  File "D:/Desktop/PARL_develop_examples_tutorials (1)/examples/parl2_dygraph_new/lesson5/homework/ddpg_quadrotor/train.py", line 122, in run_evaluate_episodes
    env.render()
  File "D:/Desktop/PARL_develop_examples_tutorials (1)/examples/parl2_dygraph_new/lesson5/homework/ddpg_quadrotor/train.py", line 59, in render
    self.env.render()
  File "D:\Anaconda\envs\paddlepaddle\lib\site-packages\rlschool\quadrotor\env.py", line 169, in render
    z_offset=self.z_offset)
  File "D:\Anaconda\envs\paddlepaddle\lib\site-packages\rlschool\quadrotor\render.py", line 494, in __init__
    debug_mode=debug_mode)
  File "D:\Anaconda\envs\paddlepaddle\lib\site-packages\rlschool\quadrotor\render.py", line 117, in __init__
    self._initialize(init_drone_z)
  File "D:\Anaconda\envs\paddlepaddle\lib\site-packages\rlschool\quadrotor\render.py", line 130, in _initialize
    self._add_drone()
  File "D:\Anaconda\envs\paddlepaddle\lib\site-packages\rlschool\quadrotor\render.py", line 152, in _add_drone
    if geometry_hash(geom) == self.drone_vertex_list_hash:
  File "D:\Anaconda\envs\paddlepaddle\lib\site-packages\rlschool\quadrotor\utils.py", line 113, in geometry_hash
    md5 += str(geometry.visual.crc())
AttributeError: 'ColorVisuals' object has no attribute 'crc'

Process finished with exit code 1
