### ISSUE TITLE
最新的代码，需要什么版本的python？

### ISSUE THREAD

**Issue by 15951836388** [PaddlePaddle/PARL#994]
3.8 3.9 3.10 全试过了，都会报错

**Comment by TomorrowIsAnOtherDay** [comment]
hello，报错信息贴一下，另外请提供下你的系统信息以及paddle/parl版本信息。

**Comment by 15951836388** [comment]
运行QuickStart 

D:\work\new\Python\Learn\venv\Scripts\python.exe D:\work\new\Python\Learn\QuickStart\train.py 
[11-24 21:38:53 MainThread @logger.py:242] Argv: D:\work\new\Python\Learn\QuickStart\train.py
Error: Can not import paddle core while this file exists: D:\work\new\Python\Learn\venv\lib\site-packages\paddle\fluid\libpaddle.pyd
[11-24 21:38:53 MainThread @utils.py:85] WRN import paddle error:
DLL load failed while importing libpaddle: 找不到指定的模块。
[11-24 21:38:54 MainThread @__init__.py:37] WRN No deep learning framework was found, but it's ok for parallel computation.
Traceback (most recent call last):
  File "D:\work\new\Python\Learn\QuickStart\train.py", line 20, in <module>
    from parl.env.compat_wrappers import CompatWrapper
  File "D:\work\new\Python\Learn\venv\lib\site-packages\parl\env\__init__.py", line 16, in <module>
    from parl.env.atari_wrappers import *
  File "D:\work\new\Python\Learn\venv\lib\site-packages\parl\env\atari_wrappers.py", line 25, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

进程已结束,退出代码1

用的cpu版本  amd
python-3.10.8-amd64
win10 
parl 2.1 
paddlepaddle 2.4

**Comment by 15951836388** [comment]
运行 examples\tutorials\lesson2\sarsa

D:\work\new\Python\Learn\venv\Scripts\python.exe D:\work\new\Python\Learn\sarsa\train.py 
Traceback (most recent call last):
  File "D:\work\new\Python\Learn\sarsa\train.py", line 93, in <module>
    main()
  File "D:\work\new\Python\Learn\sarsa\train.py", line 79, in main
    ep_reward, ep_steps = run_episode(env, agent, is_render)
  File "D:\work\new\Python\Learn\sarsa\train.py", line 29, in run_episode
    action = agent.sample(obs)  # 根据算法选择一个动作
  File "D:\work\new\Python\Learn\sarsa\agent.py", line 36, in sample
    action = self.predict(obs)
  File "D:\work\new\Python\Learn\sarsa\agent.py", line 43, in predict
    Q_list = self.Q[obs, :]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

进程已结束,退出代码1

**Comment by ShuaibinLi** [comment]
> 

可以通过 `pip install opencv-python` 安装缺少cv2依赖包。

**Comment by ShuaibinLi** [comment]
window建议使用conda虚拟环境，建议优先使用python3.8，paddlepaddle2.3.1
